/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 1997-2007 Sun Microsystems, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. You can obtain a copy of the License at
 * http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  When distributing the software, include this License Header
 * Notice in each file and include the License file at
 * nbbuild/licenses/CDDL-GPL-2-CP.  Sun designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Sun in the GPL Version 2 section of the License file that
 * accompanied this code. If applicable, add the following below the
 * License Header, with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * Contributor(s):
 *
 * The Original Software is NetBeans. The Initial Developer of the Original
 * Software is Sun Microsystems, Inc. Portions Copyright 1997-2006 Sun
 * Microsystems, Inc. All Rights Reserved.
 *
 * If you wish your version of this file to be governed by only the CDDL
 * or only the GPL Version 2, indicate your decision by adding
 * "[Contributor] elects to include this software in this distribution
 * under the [CDDL or GPL Version 2] license." If you do not indicate a
 * single choice of license, a recipient has the option to distribute
 * your version of this file under either the CDDL, the GPL Version 2 or
 * to extend the choice of license to its licensees as provided above.
 * However, if you add GPL Version 2 code and therefore, elected the GPL
 * Version 2 license, then the option applies only if the new code is
 * made subject to such option by the copyright holder.
 */

package org.netbeans.modules.jackpot.ui;

import javax.swing.event.DocumentListener;

/**
 * Form to edit an inspection's query and refactoring descriptions.
 */
public class NewQueryPanel extends javax.swing.JPanel {
    
    public NewQueryPanel() {
        initComponents();
    }

    public String getQueryName() {
        return queryNameTextField.getText();
    }

    public void setQueryName(String newName) {
        queryNameTextField.setText(newName);
    }

    public String getRefactoringName() {
        return refactoringNameTextField.getText();
    }

    public void setRefactoringName(String newName) {
        refactoringNameTextField.setText(newName);
    }
    
    public String getDescription() {
        return descriptionTextArea.getText();
    }
    
    public void setDescription(String desc) {
        descriptionTextArea.setText(desc);
    }
     
    public void addDocumentListener(DocumentListener l) {
        queryNameTextField.getDocument().addDocumentListener(l);
    }
    
    public void removeDocumentListener(DocumentListener l) {
        queryNameTextField.getDocument().removeDocumentListener(l);
    }
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        descriptionLabel = new javax.swing.JLabel();
        descriptionScroller = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        queryLabel = new javax.swing.JLabel();
        queryNameTextField = new javax.swing.JTextField();
        refactoringLabel = new javax.swing.JLabel();
        refactoringNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        descriptionLabel.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/jackpot/ui/Bundle").getString("MSG_EditQuery_Description"));

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        descriptionScroller.setViewportView(descriptionTextArea);

        queryLabel.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/jackpot/ui/Bundle").getString("LBL_Query_Name"));

        refactoringLabel.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/jackpot/ui/Bundle").getString("LBL_Refactoring_Name"));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel1.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/jackpot/ui/Bundle").getString("MSG_NewQuery_Note"));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, descriptionScroller, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, descriptionLabel)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(queryLabel)
                            .add(refactoringLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(refactoringNameTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .add(queryNameTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(queryLabel)
                    .add(queryNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(refactoringLabel)
                    .add(refactoringNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(12, 12, 12)
                .add(descriptionLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(descriptionScroller, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JScrollPane descriptionScroller;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel queryLabel;
    private javax.swing.JTextField queryNameTextField;
    private javax.swing.JLabel refactoringLabel;
    private javax.swing.JTextField refactoringNameTextField;
    // End of variables declaration//GEN-END:variables
    
}
