/*
 * File:           Command_descriptionHandler.java
 * Date:           March 13, 2004  10:23 PM
 *
 * @author  lahvac
 * @version generated by NetBeans XML module
 */
package org.netbeans.modules.latex.model.command;

import org.xml.sax.*;

/*package private*/ interface Command_descriptionHandler {
    
    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_argument(final AttributeList meta) throws SAXException;
    
    /**
     *
     * A container element end event handling method.
     */
    public void end_argument() throws SAXException;
    
    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_value(final AttributeList meta) throws SAXException;
    
    /**
     *
     * A container element end event handling method.
     */
    public void end_value() throws SAXException;
    
    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_commands(final AttributeList meta) throws SAXException;
    
    /**
     *
     * A container element end event handling method.
     */
    public void end_commands() throws SAXException;
    
    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_includes(final AttributeList meta) throws SAXException;
    
    /**
     *
     * A container element end event handling method.
     */
    public void end_includes() throws SAXException;
    
    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_attribute(final AttributeList meta) throws SAXException;
    
    /**
     *
     * A container element end event handling method.
     */
    public void end_attribute() throws SAXException;
    
    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_file(final AttributeList meta) throws SAXException;
    
    /**
     *
     * A container element end event handling method.
     */
    public void end_file() throws SAXException;
    
    /**
     *
     * An empty element event handling method.
     * @param data value or null
     */
    public void handle_include(final AttributeList meta) throws SAXException;
    
    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_environment(final AttributeList meta) throws SAXException;
    
    /**
     *
     * A container element end event handling method.
     */
    public void end_environment() throws SAXException;
    
    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_options(final AttributeList meta) throws SAXException;
    
    /**
     *
     * A container element end event handling method.
     */
    public void end_options() throws SAXException;
    
    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_command(final AttributeList meta) throws SAXException;
    
    /**
     *
     * A container element end event handling method.
     */
    public void end_command() throws SAXException;
    
    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_option(final AttributeList meta) throws SAXException;
    
    /**
     *
     * A container element end event handling method.
     */
    public void end_option() throws SAXException;
    
    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_counter(final AttributeList meta) throws SAXException;
    
    /**
     *
     * A container element end event handling method.
     */
    public void end_counter() throws SAXException;
    
    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_counters(final AttributeList meta) throws SAXException;
    
    /**
     *
     * A container element end event handling method.
     */
    public void end_counters() throws SAXException;
    
    /**
     *
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     */
    public void handle_description(final java.lang.String data, final AttributeList meta) throws SAXException;
    
    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_environments(final AttributeList meta) throws SAXException;
    
    /**
     *
     * A container element end event handling method.
     */
    public void end_environments() throws SAXException;
    
}

