/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 1997-2007 Sun Microsystems, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. You can obtain a copy of the License at
 * http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  When distributing the software, include this License Header
 * Notice in each file and include the License file at
 * nbbuild/licenses/CDDL-GPL-2-CP.  Sun designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Sun in the GPL Version 2 section of the License file that
 * accompanied this code. If applicable, add the following below the
 * License Header, with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * Contributor(s):
 *
 * The Original Software is NetBeans. The Initial Developer of the Original
 * Software is Sun Microsystems, Inc. Portions Copyright 1997-2006 Sun
 * Microsystems, Inc. All Rights Reserved.
 *
 * If you wish your version of this file to be governed by only the CDDL
 * or only the GPL Version 2, indicate your decision by adding
 * "[Contributor] elects to include this software in this distribution
 * under the [CDDL or GPL Version 2] license." If you do not indicate a
 * single choice of license, a recipient has the option to distribute
 * your version of this file under either the CDDL, the GPL Version 2 or
 * to extend the choice of license to its licensees as provided above.
 * However, if you add GPL Version 2 code and therefore, elected the GPL
 * Version 2 license, then the option applies only if the new code is
 * made subject to such option by the copyright holder.
 */


package beans2nbm.ui;

import java.awt.Component;
import javax.swing.JDialog;
import javax.swing.JRadioButton;
import javax.swing.SwingUtilities;
import org.netbeans.spi.wizard.WizardPage;

/**
 *
 * @author  Tim Boudreau
 */
public class SelectTaskPanel extends WizardPage {

    /** Creates new form SelectTaskPanel */
    public SelectTaskPanel() {
        initComponents();
    }

    public static String getStep() {
        return "taskChoice";
    }

    public static String getDescription() {
        return "Pick Module Type";
    }

public String getID() {
        return getStep();
    }

    protected String validateContents(Component component, Object event) {
        String selName = null;
        Component[] c = getComponents();
        for (int i=0; i < c.length; i++) {
            if (c[i] instanceof JRadioButton) {
                JRadioButton jb = (JRadioButton) c[i];
                if (jb.isSelected()) {
                    selName = jb.getName();
                    assert selName != null : "Unnamed radio button present:" + jb;
                }
            }
        }
        if (selName == null) {
            return "Select a task";
        } else {
            if (selName == beanModule.getName()) {
                putWizardData("title", "BeanNetter - Create a plugin for Swing/AWT components");
            } else if (selName == libModule.getName()) {
                putWizardData("title", "BeanNetter - Create a plugin to provide a library");
            } else if (selName == lafModule.getName()) {
                putWizardData("title", "BeanNetter - Create a plugin to provide a look and feel");
            } else {
                putWizardData("title", null);
            }
            updateDlgTitle();
        }
        return null;
    }

    public void addNotify() {
        super.addNotify();
        updateDlgTitle();
    }

    private void updateDlgTitle() {
        JDialog dlg = (JDialog) SwingUtilities.getAncestorOfClass(JDialog.class, this);
        if (dlg != null) {
            String ttl = (String) getWizardData ("title");
            if (ttl == null) {
                dlg.setTitle ("BeanNetter - the NetBeans Module Generator");
            } else {
                dlg.setTitle (ttl);
            }
        }
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        beanModule = new javax.swing.JRadioButton();
        libModule = new javax.swing.JRadioButton();
        lafModule = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 375));
        setLayout(new java.awt.GridBagLayout());

        buttonGroup1.add(beanModule);
        beanModule.setText("Create a Module that adds some Swing/AWT components to the palette");
        beanModule.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        beanModule.setMargin(new java.awt.Insets(0, 0, 0, 0));
        beanModule.setName("beansModule");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(beanModule, gridBagConstraints);

        buttonGroup1.add(libModule);
        libModule.setText("Create a Module that provides a library");
        libModule.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        libModule.setMargin(new java.awt.Insets(0, 0, 0, 0));
        libModule.setName("libsModule");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        add(libModule, gridBagConstraints);

        buttonGroup1.add(lafModule);
        lafModule.setText("Create a module that installs a Look and Feel");
        lafModule.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lafModule.setEnabled(false);
        lafModule.setMargin(new java.awt.Insets(0, 0, 0, 0));
        lafModule.setName("lafModule");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        add(lafModule, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton beanModule;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton lafModule;
    private javax.swing.JRadioButton libModule;
    // End of variables declaration//GEN-END:variables
    
}
