#!/bin/sh
# XXX set in branch e.g.: download_url_base=http://dlc.sun.com.edgesuite.net/netbeans/6.9/final/zip/netbeans-6.9-201006101454
if [ \! -f .hg/nbsrc.zip ]
then
  wget -O .hg/nbsrc.zip --progress=dot:mega "${download_url_base}-src.zip"
fi
if [ \! -f .hg/nb.zip ]
then
  wget -O .hg/nb.zip --progress=dot:mega "${download_url_base}-ml.zip"
fi
unzip .hg/nb.zip
mkdir nb_all
(cd nb_all; unzip ../.hg/nbsrc.zip)
ln -sv .. nb_all/contrib
ant -f nb_all/nbbuild/build.xml bootstrap
for m in `cat nb_all/contrib/other/hudson-build-list`; do ant -f nb_all/contrib/"$m"/build.xml -Dnetbeans.dest.dir=$WORKSPACE/netbeans -Dbuildnumber=$BUILD_TAG nbm; done
ant -f nb_all/contrib/other/hudson-build-update-descriptor.xml
