/*
 *                 Sun Public License Notice
 * 
 * The contents of this file are subject to the Sun Public License
 * Version 1.0 (the "License"). You may not use this file except in
 * compliance with the License. A copy of the License is available at
 * http://www.sun.com/
 * 
 * The Original Code is NetBeans. The Initial Developer of the Original
 * Code is Sun Microsystems, Inc. Portions Copyright 1997-2003 Sun
 * Microsystems, Inc. All Rights Reserved.
 */

package org.netbeans.modules.helpbuilder.ui;

import org.netbeans.modules.helpbuilder.*;
import java.awt.Component;
import java.io.File;
import java.net.URL;
import java.net.MalformedURLException;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import org.openide.WizardDescriptor;
import org.openide.util.HelpCtx;
import org.openide.util.NbBundle;

/** 
 *
 * @author  Richard Gregor
 */
public class AddIndexPanel extends javax.swing.JPanel {    
    public static JButton OK_OPTION;
    public static JButton CANCEL_OPTION;
    
    public AddIndexPanel() {        
        initComponents ();                
        setName(NbBundle.getMessage(AddPanel.class, "TITLE_AddPanel")); 
        OK_OPTION = new JButton(NbBundle.getMessage(AddPanel.class, "LBL_OK_OPTION"));
        OK_OPTION.setMnemonic(NbBundle.getMessage(AddPanel.class, "ACS_OK_OPTION_mnc").charAt(0));
        CANCEL_OPTION = new JButton(NbBundle.getMessage(AddPanel.class, "LBL_CANCEL_OPTION"));
        CANCEL_OPTION.setMnemonic(NbBundle.getMessage(AddPanel.class, "ACS_CANCEL_OPTION_mnc").charAt(0));
        OK_OPTION.setEnabled(false);
        javax.swing.event.DocumentListener docList = new javax.swing.event.DocumentListener() {
                public void insertUpdate(javax.swing.event.DocumentEvent e) {                    
                    setOK_OPTION();
                }
                public void removeUpdate(javax.swing.event.DocumentEvent e) {
                    setOK_OPTION();                   
                }
                public void changedUpdate(javax.swing.event.DocumentEvent e) {                  
                    setOK_OPTION();
                }
        }; 
        txName.getDocument().addDocumentListener(docList);
        txtURL.getDocument().addDocumentListener(docList);
        
    }
    
    private void setOK_OPTION(){
        String name = txName.getText();
        String url = txtURL.getText();
        if((name != null)&&(name.length() > 0)&&(url != null)&&(url.length() > 0))
            OK_OPTION.setEnabled(true);
        else
            OK_OPTION.setEnabled(false);
    }
        

    public Object[] getOptions(){
        Object options[] = {OK_OPTION,CANCEL_OPTION};
        return options;
    }
    
    public void setName(String name){
        txName.setText(name);
    }
    
    public String getName(){
        return txName.getText();
    }
    
    public void setUrlSpec(String url){
        txtURL.setText(url);
    }
    
    public String getUrlSpec(){
        return txtURL.getText();
    }
    
    
    // --- VISUAL DESIGN OF PANEL ---

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        centerPanel = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblURL = new javax.swing.JLabel();
        urlPanel = new javax.swing.JPanel();
        txtURL = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();
        bottomPanel = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        setMinimumSize(new java.awt.Dimension(700, 417));
        setPreferredSize(new java.awt.Dimension(515, 150));
        centerPanel.setLayout(new java.awt.GridBagLayout());

        lblName.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("org/netbeans/modules/helpbuilder/ui/Bundle").getString("ACS_lblTitle_mnc").charAt(0));
        lblName.setLabelFor(txName);
        lblName.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/helpbuilder/ui/Bundle").getString("lblName"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        centerPanel.add(lblName, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 12);
        centerPanel.add(txName, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weighty = 1.0;
        centerPanel.add(jPanel1, gridBagConstraints);

        lblURL.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("org/netbeans/modules/helpbuilder/ui/Bundle").getString("ACS_lblURL_mnc").charAt(0));
        lblURL.setLabelFor(txtURL);
        lblURL.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/helpbuilder/ui/Bundle").getString("lblURL"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        centerPanel.add(lblURL, gridBagConstraints);

        urlPanel.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        urlPanel.add(txtURL, gridBagConstraints);

        btnBrowse.setMnemonic(java.util.ResourceBundle.getBundle("org/netbeans/modules/helpbuilder/ui/Bundle").getString("ACS_btnBrowse_mnc").charAt(0));
        btnBrowse.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/helpbuilder/ui/Bundle").getString("LBL_btnBrowse"));
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 12);
        urlPanel.add(btnBrowse, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        centerPanel.add(urlPanel, gridBagConstraints);

        add(centerPanel, java.awt.BorderLayout.CENTER);

        add(topPanel, java.awt.BorderLayout.NORTH);

        add(bottomPanel, java.awt.BorderLayout.SOUTH);

        add(rightPanel, java.awt.BorderLayout.EAST);

        leftPanel.setLayout(new java.awt.GridBagLayout());

        add(leftPanel, java.awt.BorderLayout.WEST);

    }//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(chooser.FILES_ONLY);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            if(file != null)
                txtURL.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    public void clear(){        
        txName.setText("");
        txtURL.setText("");
    }
        
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextField txName;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel urlPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblURL;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTextField txtURL;
    private javax.swing.JPanel bottomPanel;
    // End of variables declaration//GEN-END:variables



}
