/*
 *                 Sun Public License Notice
 * 
 * The contents of this file are subject to the Sun Public License
 * Version 1.0 (the "License"). You may not use this file except in
 * compliance with the License. A copy of the License is available at
 * http://www.sun.com/
 * 
 * The Original Code is NetBeans. The Initial Developer of the Original
 * Code is Sun Microsystems, Inc. Portions Copyright 1997-2003 Sun
 * Microsystems, Inc. All Rights Reserved.
 */

package org.netbeans.modules.helpbuilder.ui;

import java.awt.Component;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.net.URL;
import java.net.MalformedURLException;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.netbeans.modules.helpbuilder.ShowHelpAction;
import org.netbeans.modules.helpbuilder.processors.HelpSetProcessor;
import org.netbeans.modules.helpbuilder.processors.MapProcessor;
import org.netbeans.modules.helpbuilder.tree.HelpTreeNode;
import org.openide.ErrorManager;
import org.openide.util.Lookup;

import org.openide.util.NbBundle;

/** A single panel for a wizard.
 * You probably want to make a wizard iterator to hold it.
 *
 * @author  rg125988
 */
public class ProjectFinishPanel extends javax.swing.JPanel {
    private String location;

    /** Create the wizard panel and set up some basic properties. */
    public ProjectFinishPanel() {
        location = ProjectSetupPanel.getTargetLocation()+File.separator;
        ClassLoader loader = (ClassLoader) Lookup.getDefault().lookup(ClassLoader.class);         
        initComponents ();
        // Provide a name in the title bar.
        setName(NbBundle.getMessage(ProjectFinishPanel.class, "TITLE_ProjectFinishPanel"));
        /*
        // Optional: provide a special description for this pane.
        // You must have turned on WizardDescriptor.WizardPanel_helpDisplayed
        // (see descriptor in standard iterator template for an example of this).
        try {
            putClientProperty ("WizardPanel_helpURL", // NOI18N
                new URL ("nbresloc:/wizard/Step3PanelHelp.html")); // NOI18N
        } catch (MalformedURLException mfue) {
            throw new IllegalStateException (mfue.toString ());
        }
        */
    }

    // --- VISUAL DESIGN OF PANEL ---

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        text = new javax.swing.JTextArea();

        setLayout(new java.awt.GridBagLayout());

        text.setBackground((java.awt.Color) javax.swing.UIManager.getDefaults().get("Button.background"));
        text.setEditable(false);
        text.setForeground((java.awt.Color) javax.swing.UIManager.getDefaults().get("CheckBoxMenuItem.acceleratorForeground"));
        text.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/helpbuilder/ui/Bundle").getString("txtProjectFinishPanel"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        add(text, gridBagConstraints);

    }//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables


}
