/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 1997-2007 Sun Microsystems, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. You can obtain a copy of the License at
 * http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  When distributing the software, include this License Header
 * Notice in each file and include the License file at
 * nbbuild/licenses/CDDL-GPL-2-CP.  Sun designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Sun in the GPL Version 2 section of the License file that
 * accompanied this code. If applicable, add the following below the
 * License Header, with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * Contributor(s):
 *
 * The Original Software is NetBeans. The Initial Developer of the Original
 * Software is Sun Microsystems, Inc. Portions Copyright 1997-2006 Sun
 * Microsystems, Inc. All Rights Reserved.
 *
 * If you wish your version of this file to be governed by only the CDDL
 * or only the GPL Version 2, indicate your decision by adding
 * "[Contributor] elects to include this software in this distribution
 * under the [CDDL or GPL Version 2] license." If you do not indicate a
 * single choice of license, a recipient has the option to distribute
 * your version of this file under either the CDDL, the GPL Version 2 or
 * to extend the choice of license to its licensees as provided above.
 * However, if you add GPL Version 2 code and therefore, elected the GPL
 * Version 2 license, then the option applies only if the new code is
 * made subject to such option by the copyright holder.
 */

package org.netbeans.modules.corba.wizard.panels;

import org.netbeans.modules.corba.wizard.IDLWizardData;
import org.openide.loaders.TemplateWizard;
import org.netbeans.modules.corba.wizard.CorbaWizard;
/**
 *
 * @author  tzezula
 */
public class SelectSourcePanel extends AbstractIDLWizardPanel implements javax.swing.event.ChangeListener {

    private javax.swing.ButtonGroup group;
    private IDLWizardData data;

    /** Creates new form SelectSourcePanel */
    public SelectSourcePanel(IDLWizardData data) {
        this.data = data;
        initComponents();
        this.group = new javax.swing.ButtonGroup();
        this.group.add (this.jRadioButton1);
        this.group.add (this.jRadioButton2);
        this.jRadioButton1.setSelected (true);
        this.jRadioButton1.addChangeListener (this);
        this.jRadioButton2.addChangeListener (this);
        this.setName(bundle.getString("TXT_CreateImport"));
        putClientProperty(CorbaWizard.PROP_CONTENT_SELECTED_INDEX, new Integer(1));
        this.jRadioButton1.setMnemonic (this.bundle.getString("TXT_NewIDL_MNE").charAt(0));
        this.jRadioButton2.setMnemonic (this.bundle.getString("TXT_IDLFromIR_MNE").charAt(0));
        this.getAccessibleContext().setAccessibleDescription (this.getAccessibleContext().getAccessibleDescription()+this.bundle.getString("TXT_ChooseIDLSource"));
        this.jRadioButton1.getAccessibleContext().setAccessibleDescription("AD_NewIDL");
        this.jRadioButton2.getAccessibleContext().setAccessibleDescription("AD_IDLFromIR");
        this.getAccessibleContext().setAccessibleDescription (this.bundle.getString("AD_SelectSourcePanel"));
    }
    
    
    public void readIDLSettings (TemplateWizard data) {
    }
    
    public void storeIDLSettings (TemplateWizard data) {
    }
    
    public boolean isValid () {
        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        setPreferredSize(new java.awt.Dimension(500, 300));
        setMinimumSize(new java.awt.Dimension(247, 194));
        jRadioButton1.setText(bundle.getString("TXT_NewIDL"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 6, 12);
        add(jRadioButton1, gridBagConstraints);

        jRadioButton2.setText(bundle.getString("TXT_IDLFromIR"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 12, 12);
        add(jRadioButton2, gridBagConstraints);

        jLabel2.setText(bundle.getString("TXT_ChooseIDLSource"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 6, 12);
        add(jLabel2, gridBagConstraints);

    }//GEN-END:initComponents

    public void stateChanged(javax.swing.event.ChangeEvent event) {
        this.data.importIdl (this.jRadioButton2.isSelected());
        this.fireChange (this);
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables

    private static final java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/netbeans/modules/corba/wizard/panels/Bundle");    

}
