/*
 *                 Sun Public License Notice
 *
 * The contents of this file are subject to the Sun Public License
 * Version 1.0 (the "License"). You may not use this file except in
 * compliance with the License. A copy of the License is available at
 * http://www.sun.com/
 *
 * The Original Code is NetBeans. The Initial Developer of the Original
 * Code is Sun Microsystems, Inc. Portions Copyright 1997-2005 Sun
 * Microsystems, Inc. All Rights Reserved.
 */

package org.netbeans.modules.latex.refactoring.ui;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JComponent;
import javax.swing.SwingUtilities;
import org.netbeans.api.progress.ProgressHandle;
import org.netbeans.api.progress.ProgressHandleFactory;
import org.netbeans.modules.latex.refactoring.FindUsagesPerformer;
import org.netbeans.modules.latex.refactoring.RefactorPerformer;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.view.BeanTreeView;
import org.openide.filesystems.FileObject;
import org.openide.util.RequestProcessor;
import org.openide.windows.TopComponent;

/**
 *
 * @author Jan Lahoda
 */
public class UsagesPanel extends javax.swing.JPanel implements ExplorerManager.Provider {
    
    private ExplorerManager manager;
    private FindUsagesPerformer findUsages;
    private String name;
    private RequestProcessor.Task performer;
    private RefactorPerformer refactor;
    private TopComponent parent;
    private List<? extends org.netbeans.modules.latex.model.command.Node> result;
    
    /** Creates new form UsagesPanel */
    public UsagesPanel(FindUsagesPerformer findUsages, RefactorPerformer refactor, String name, TopComponent parent) {
        initComponents();
        manager = new ExplorerManager();
        
        usagesPanel.setLayout(new BorderLayout());
        usagesPanel.add(new BeanTreeView(), BorderLayout.CENTER);
        
        progress.setLayout(new BorderLayout());
        
        this.findUsages = findUsages;
        this.refactor = refactor;
        this.name = name;
        this.parent = parent;
        
        if (refactor == null) {
            refactorButton.setEnabled(false);
            cancelCloseButton.setText("Close");
        }
        
        performer = RequestProcessor.getDefault().create(new FindUsagesImpl());
        
        performer.schedule(0);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        usagesPanel = new javax.swing.JPanel();
        progress = new javax.swing.JPanel();
        refactorButton = new javax.swing.JButton();
        cancelCloseButton = new javax.swing.JButton();

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/netbeans/modules/latex/refactoring/resources/refresh.png")));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/netbeans/modules/latex/refactoring/resources/prevmatch.png")));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/netbeans/modules/latex/refactoring/resources/nextmatch.png")));

        org.jdesktop.layout.GroupLayout usagesPanelLayout = new org.jdesktop.layout.GroupLayout(usagesPanel);
        usagesPanel.setLayout(usagesPanelLayout);
        usagesPanelLayout.setHorizontalGroup(
            usagesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 320, Short.MAX_VALUE)
        );
        usagesPanelLayout.setVerticalGroup(
            usagesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 213, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout progressLayout = new org.jdesktop.layout.GroupLayout(progress);
        progress.setLayout(progressLayout);
        progressLayout.setHorizontalGroup(
            progressLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 320, Short.MAX_VALUE)
        );
        progressLayout.setVerticalGroup(
            progressLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 26, Short.MAX_VALUE)
        );

        refactorButton.setText("Refactor...");
        refactorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refactorButtonActionPerformed(evt);
            }
        });

        cancelCloseButton.setText("Cancel");
        cancelCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelCloseButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jButton1)
                            .add(jButton2)
                            .add(jButton3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(usagesPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(68, 68, 68)
                        .add(refactorButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cancelCloseButton))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(68, 68, 68)
                        .add(progress, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton3))
                    .add(usagesPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(progress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(refactorButton)
                    .add(cancelCloseButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refactorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refactorButtonActionPerformed
        RequestProcessor.getDefault().post(new RefactorImpl());
    }//GEN-LAST:event_refactorButtonActionPerformed

    private void cancelCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelCloseButtonActionPerformed
        parent.close();
    }//GEN-LAST:event_cancelCloseButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        performer.schedule(0);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cancelCloseButton;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JPanel progress;
    public javax.swing.JButton refactorButton;
    public javax.swing.JPanel usagesPanel;
    // End of variables declaration//GEN-END:variables

    public void setUsages(List<? extends org.netbeans.modules.latex.model.command.Node> result) {
        Map<FileObject, List<org.netbeans.modules.latex.model.command.Node>> file2Node = new HashMap();
        
        for (org.netbeans.modules.latex.model.command.Node n : result) {
            FileObject file = (FileObject) n.getStartingPosition().getFile();
            List<org.netbeans.modules.latex.model.command.Node> l = file2Node.get(file);
            
            if (l == null) {
                file2Node.put(file, l = new ArrayList());
            }
            
            l.add(n);
        }
        
        manager.setRootContext(new UsagesRootNode(file2Node, name));
    }

    public ExplorerManager getExplorerManager() {
        return manager;
    }
    
    private final class FindUsagesImpl implements Runnable {
        
        private JComponent comp;
        
        public void run() {
            final ProgressHandle handle = ProgressHandleFactory.createHandle("Find Usages");
            
            SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                    progress.add(comp = ProgressHandleFactory.createProgressComponent(handle), BorderLayout.CENTER);
                }
            });
            
            result = findUsages.perform(handle);
            
            setUsages(result);
            
            SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                    progress.remove(comp);
                }
            });
        }
        
    }
    
    private final class RefactorImpl implements Runnable {
        
        private JComponent comp;
        
        public void run() {
            final ProgressHandle handle = ProgressHandleFactory.createHandle("Refactoring");
            
            SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                    progress.add(comp = ProgressHandleFactory.createProgressComponent(handle), BorderLayout.CENTER);
                }
            });
            
            refactor.refactor(result, handle);
            
            SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                    progress.remove(comp);
                    parent.close();
                }
            });
        }
        
    }
    
}
