/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2008 Sun Microsystems, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. You can obtain a copy of the License at
 * http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  When distributing the software, include this License Header
 * Notice in each file and include the License file at
 * nbbuild/licenses/CDDL-GPL-2-CP.  Sun designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Sun in the GPL Version 2 section of the License file that
 * accompanied this code. If applicable, add the following below the
 * License Header, with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * If you wish your version of this file to be governed by only the CDDL
 * or only the GPL Version 2, indicate your decision by adding
 * "[Contributor] elects to include this software in this distribution
 * under the [CDDL or GPL Version 2] license." If you do not indicate a
 * single choice of license, a recipient has the option to distribute
 * your version of this file under either the CDDL, the GPL Version 2 or
 * to extend the choice of license to its licensees as provided above.
 * However, if you add GPL Version 2 code and therefore, elected the GPL
 * Version 2 license, then the option applies only if the new code is
 * made subject to such option by the copyright holder.
 *
 * Contributor(s):
 *
 * Portions Copyrighted 2008 Sun Microsystems, Inc.
 */

package org.netbeans.modules.ada.project.ui.options;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.jdesktop.layout.GroupLayout;
import org.jdesktop.layout.LayoutStyle;
import org.openide.awt.Mnemonics;
import org.openide.util.ChangeSupport;
import org.openide.util.NbBundle;

/**
 * @author  Tomas Mysik
 */
public class AdaOptionsPanel extends JPanel {

    private final ChangeSupport changeSupport = new ChangeSupport(this);

    public AdaOptionsPanel() {
        initComponents();
        errorLabel.setText(" "); // NOI18N

        // listeners
        DocumentListener documentListener = new DefaultDocumentListener();
    }

    public void setError(String message) {
        errorLabel.setText(" "); // NOI18N
        errorLabel.setForeground(UIManager.getColor("nb.errorForeground")); // NOI18N
        errorLabel.setText(message);
    }

    public void setWarning(String message) {
        errorLabel.setText(" "); // NOI18N
        errorLabel.setForeground(UIManager.getColor("nb.warningForeground")); // NOI18N
        errorLabel.setText(message);
    }

    public void addChangeListener(ChangeListener listener) {
        changeSupport.addChangeListener(listener);
    }

    public void removeChangeListener(ChangeListener listener) {
        changeSupport.removeChangeListener(listener);
    }

    void fireChange() {
        changeSupport.fireChange();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {












        standardsLabel = new JLabel();
        standardsLineSeparator = new JSeparator();
        adaDialectsLabel = new JLabel();
        namingLabel = new JLabel();
        namingLineSeparator = new JSeparator();
        errorLabel = new JLabel();
        adaRestrictionsLabel = new JLabel();
        adaDialectsComboBox = new JComboBox();
        adaRestrictionsComboBox = new JComboBox();
        pkgSpecMaskLabel = new JLabel();
        pkgBodyMaskLabel = new JLabel();
        separatorMaskLabel = new JLabel();
        pkgSpecSepTextField = new JTextField();
        pkgBodySepTextField = new JTextField();
        separateSepTextField = new JTextField();
        extTitleLabel = new JLabel();
        pkgSpecPrefixComboBox = new JComboBox();
        prefixTitleLabel = new JLabel();
        pkgBodyPrefixComboBox = new JComboBox();
        separatePrefixComboBox = new JComboBox();
        postfixTitleLabel = new JLabel();
        pkgSpecPostfixComboBox = new JComboBox();
        pkgBodyPostfixComboBox = new JComboBox();
        separatePostfixComboBox = new JComboBox();
        pkgSpecExtComboBox = new JComboBox();
        pkgBodyExtComboBox = new JComboBox();
        separateExtComboBox = new JComboBox();
        separatorTitleLabel = new JLabel();
        Mnemonics.setLocalizedText(standardsLabel, NbBundle.getMessage(AdaOptionsPanel.class, "LBL_Standards"));
        Mnemonics.setLocalizedText(adaDialectsLabel, NbBundle.getMessage(AdaOptionsPanel.class, "LBL_AdaDialects"));
        Mnemonics.setLocalizedText(namingLabel, NbBundle.getMessage(AdaOptionsPanel.class, "LBL_Naming"));
        Mnemonics.setLocalizedText(errorLabel, "ERROR");
        Mnemonics.setLocalizedText(adaRestrictionsLabel, NbBundle.getMessage(AdaOptionsPanel.class, "LBL_adaRestrictions"));
        adaDialectsComboBox.setModel(new DefaultComboBoxModel(new String[] { "Ada 83", "Ada 95", "Ada 2005" }));

        adaRestrictionsComboBox.setModel(new DefaultComboBoxModel(new String[] { "None", "Spark", "MIL-STD-498" }));
        Mnemonics.setLocalizedText(pkgSpecMaskLabel, NbBundle.getMessage(AdaOptionsPanel.class, "LBL_pkgSpecMask"));
        Mnemonics.setLocalizedText(pkgBodyMaskLabel, NbBundle.getMessage(AdaOptionsPanel.class, "LBL_pkgBodyMask"));
        Mnemonics.setLocalizedText(separatorMaskLabel, NbBundle.getMessage(AdaOptionsPanel.class, "LBL_separatorMask"));
        Mnemonics.setLocalizedText(extTitleLabel, NbBundle.getMessage(AdaOptionsPanel.class, "LBL_extTitle"));
        pkgSpecPrefixComboBox.setModel(new DefaultComboBoxModel(new String[] { "<package name>", "<free name>" }));
        Mnemonics.setLocalizedText(prefixTitleLabel, NbBundle.getMessage(AdaOptionsPanel.class, "LBL_prefixTitle"));
        pkgBodyPrefixComboBox.setModel(new DefaultComboBoxModel(new String[] { "<package name>", "<free name>" }));

        separatePrefixComboBox.setModel(new DefaultComboBoxModel(new String[] { "<package name>", "<free name>" }));
        Mnemonics.setLocalizedText(postfixTitleLabel, NbBundle.getMessage(AdaOptionsPanel.class, "LBL_postfixTitle"));
        pkgSpecPostfixComboBox.setModel(new DefaultComboBoxModel(new String[] { "<none>", "<free name>" }));

        pkgBodyPostfixComboBox.setModel(new DefaultComboBoxModel(new String[] { "<none>", "<free name>" }));

        separatePostfixComboBox.setModel(new DefaultComboBoxModel(new String[] { "<procedure name>", "<free name>", "<none>" }));

        pkgSpecExtComboBox.setModel(new DefaultComboBoxModel(new String[] { ".ads", ".ada (deprecated)" }));

        pkgBodyExtComboBox.setModel(new DefaultComboBoxModel(new String[] { ".adb", ".ada (deprecated)" }));

        separateExtComboBox.setModel(new DefaultComboBoxModel(new String[] { ".adb", ".ada (deprecated)" }));
        Mnemonics.setLocalizedText(separatorTitleLabel, NbBundle.getMessage(AdaOptionsPanel.class, "AdaOptionsPanel.separatorTitleLabel.text"));
        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(standardsLabel)
                                .addPreferredGap(LayoutStyle.RELATED)
                                .add(standardsLineSeparator, GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
                            .add(errorLabel)
                            .add(layout.createSequentialGroup()
                                .add(12, 12, 12)
                                .add(layout.createParallelGroup(GroupLayout.LEADING)
                                    .add(adaRestrictionsLabel)
                                    .add(adaDialectsLabel, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.UNRELATED)
                                .add(layout.createParallelGroup(GroupLayout.LEADING)
                                    .add(adaRestrictionsComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .add(adaDialectsComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .add(373, 373, 373))))
                    .add(layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(layout.createParallelGroup(GroupLayout.TRAILING, false)
                            .add(GroupLayout.LEADING, pkgBodyMaskLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(GroupLayout.LEADING, pkgSpecMaskLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(GroupLayout.LEADING, separatorMaskLabel, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(GroupLayout.LEADING)
                            .add(layout.createParallelGroup(GroupLayout.TRAILING)
                                .add(layout.createParallelGroup(GroupLayout.LEADING)
                                    .add(pkgSpecPrefixComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .add(pkgBodyPrefixComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .add(prefixTitleLabel))
                            .add(separatePrefixComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(GroupLayout.LEADING)
                            .add(GroupLayout.TRAILING, pkgSpecSepTextField, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                            .add(GroupLayout.TRAILING, separatorTitleLabel))
                        .addPreferredGap(LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(GroupLayout.LEADING, false)
                            .add(pkgBodyPostfixComboBox, 0, 110, Short.MAX_VALUE)
                            .add(separatePostfixComboBox, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(pkgSpecPostfixComboBox, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(GroupLayout.TRAILING, postfixTitleLabel))
                        .addPreferredGap(LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(GroupLayout.LEADING, false)
                            .add(separateExtComboBox, 0, 0, Short.MAX_VALUE)
                            .add(pkgBodyExtComboBox, 0, 0, Short.MAX_VALUE)
                            .add(pkgSpecExtComboBox, 0, 0, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(41, 41, 41)
                                .add(extTitleLabel))))
                    .add(layout.createSequentialGroup()
                        .add(262, 262, 262)
                        .add(separateSepTextField, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.RELATED, 319, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(262, 262, 262)
                        .add(pkgBodySepTextField, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.RELATED, 319, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(namingLabel)
                        .addPreferredGap(LayoutStyle.RELATED)
                        .add(namingLineSeparator, GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(new Component[] {adaDialectsLabel, adaRestrictionsLabel}, GroupLayout.HORIZONTAL);

        layout.linkSize(new Component[] {adaDialectsComboBox, adaRestrictionsComboBox}, GroupLayout.HORIZONTAL);

        layout.linkSize(new Component[] {pkgBodyMaskLabel, pkgSpecMaskLabel, separatorMaskLabel}, GroupLayout.HORIZONTAL);

        layout.linkSize(new Component[] {pkgBodySepTextField, pkgSpecSepTextField, separateSepTextField}, GroupLayout.HORIZONTAL);

        layout.linkSize(new Component[] {pkgBodyPostfixComboBox, pkgBodyPrefixComboBox, pkgSpecPostfixComboBox, pkgSpecPrefixComboBox, separatePostfixComboBox, separatePrefixComboBox}, GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(GroupLayout.CENTER)
                    .add(standardsLineSeparator, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                    .add(standardsLabel))
                .addPreferredGap(LayoutStyle.RELATED)
                .add(layout.createParallelGroup(GroupLayout.CENTER)
                    .add(adaDialectsComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .add(adaDialectsLabel))
                .addPreferredGap(LayoutStyle.RELATED)
                .add(layout.createParallelGroup(GroupLayout.CENTER)
                    .add(adaRestrictionsComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .add(adaRestrictionsLabel))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(GroupLayout.CENTER)
                    .add(namingLineSeparator, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                    .add(namingLabel))
                .add(1, 1, 1)
                .add(layout.createParallelGroup(GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(GroupLayout.BASELINE)
                            .add(prefixTitleLabel)
                            .add(separatorTitleLabel))
                        .add(4, 4, 4)
                        .add(layout.createParallelGroup(GroupLayout.CENTER)
                            .add(pkgSpecPrefixComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .add(pkgSpecMaskLabel))
                        .addPreferredGap(LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(GroupLayout.CENTER)
                            .add(pkgBodyPrefixComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .add(pkgBodyMaskLabel))
                        .addPreferredGap(LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(GroupLayout.CENTER)
                            .add(separatePrefixComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .add(separatorMaskLabel))
                        .addPreferredGap(LayoutStyle.RELATED, 168, Short.MAX_VALUE)
                        .add(errorLabel))
                    .add(layout.createParallelGroup(GroupLayout.TRAILING)
                        .add(layout.createSequentialGroup()
                            .add(pkgSpecSepTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.RELATED)
                            .add(pkgBodySepTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.RELATED)
                            .add(separateSepTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .add(layout.createParallelGroup(GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(extTitleLabel)
                                .add(4, 4, 4)
                                .add(pkgSpecExtComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.RELATED)
                                .add(pkgBodyExtComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.RELATED)
                                .add(separateExtComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(postfixTitleLabel)
                                .add(4, 4, 4)
                                .add(pkgSpecPostfixComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.RELATED)
                                .add(pkgBodyPostfixComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.RELATED)
                                .add(separatePostfixComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JComboBox adaDialectsComboBox;
    private JLabel adaDialectsLabel;
    private JComboBox adaRestrictionsComboBox;
    private JLabel adaRestrictionsLabel;
    private JLabel errorLabel;
    private JLabel extTitleLabel;
    private JLabel namingLabel;
    private JSeparator namingLineSeparator;
    private JComboBox pkgBodyExtComboBox;
    private JLabel pkgBodyMaskLabel;
    private JComboBox pkgBodyPostfixComboBox;
    private JComboBox pkgBodyPrefixComboBox;
    private JTextField pkgBodySepTextField;
    private JComboBox pkgSpecExtComboBox;
    private JLabel pkgSpecMaskLabel;
    private JComboBox pkgSpecPostfixComboBox;
    private JComboBox pkgSpecPrefixComboBox;
    private JTextField pkgSpecSepTextField;
    private JLabel postfixTitleLabel;
    private JLabel prefixTitleLabel;
    private JComboBox separateExtComboBox;
    private JComboBox separatePostfixComboBox;
    private JComboBox separatePrefixComboBox;
    private JTextField separateSepTextField;
    private JLabel separatorMaskLabel;
    private JLabel separatorTitleLabel;
    private JLabel standardsLabel;
    private JSeparator standardsLineSeparator;
    // End of variables declaration//GEN-END:variables

    private final class DefaultDocumentListener implements DocumentListener {

        public void insertUpdate(DocumentEvent e) {
            processUpdate();
        }

        public void removeUpdate(DocumentEvent e) {
            processUpdate();
        }

        public void changedUpdate(DocumentEvent e) {
            processUpdate();
        }

        private void processUpdate() {
            fireChange();
        }
    }
}
