/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 1997-2007 Sun Microsystems, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. You can obtain a copy of the License at
 * http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  When distributing the software, include this License Header
 * Notice in each file and include the License file at
 * nbbuild/licenses/CDDL-GPL-2-CP.  Sun designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Sun in the GPL Version 2 section of the License file that
 * accompanied this code. If applicable, add the following below the
 * License Header, with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * Contributor(s):
 *
 * The Original Software is the Jabber module.
 * The Initial Developer of the Original Software is Petr Nejedly
 * Portions created by Petr Nejedly are Copyright (c) 2004.
 * All Rights Reserved.
 *
 * If you wish your version of this file to be governed by only the CDDL
 * or only the GPL Version 2, indicate your decision by adding
 * "[Contributor] elects to include this software in this distribution
 * under the [CDDL or GPL Version 2] license." If you do not indicate a
 * single choice of license, a recipient has the option to distribute
 * your version of this file under either the CDDL, the GPL Version 2 or
 * to extend the choice of license to its licensees as provided above.
 * However, if you add GPL Version 2 code and therefore, elected the GPL
 * Version 2 license, then the option applies only if the new code is
 * made subject to such option by the copyright holder.
 *
 * Contributor(s): Petr Nejedly
 */

package org.netbeans.modules.jabber.ui;

import java.awt.Dialog;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import javax.swing.SwingUtilities;
import org.netbeans.modules.jabber.Contact;
import org.netbeans.modules.jabber.Manager;
import org.netbeans.modules.jabber.Result;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;

/**
 *
 * @author  nenik
 */
public class RemoveContactUI extends javax.swing.JPanel {


    public static void removeContacts(Contact[] contacts) {
        Manager man = contacts[0].getManager();
        new RemoveContactUI(man, contacts).doRemove();

    }
    
    
    private Manager manager;
    private Contact[] toRemove;
    private Result result;
    Dialog d;

    
    /** Creates new form RemoveContactUI */
    private  RemoveContactUI(Manager man, Contact[] contacts) {
        manager = man;
        toRemove = contacts;
        
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        cancelButton = new javax.swing.JButton();
        list = new javax.swing.JLabel();

        cancelButton.setText("Cancel");
        cancelButton.setMinimumSize(new java.awt.Dimension(200, 100));

        setLayout(new java.awt.BorderLayout());

        add(list, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel list;
    // End of variables declaration//GEN-END:variables


    
    private void doRemove() {
        // prepare listener
        Lst listener = new Lst();
        
        StringBuffer listBuffer = new StringBuffer();
        Contact.List cList = manager.getContactList();

        for (int i = 0; i<toRemove.length; i++ ) {
            listBuffer.append(cList.getLongDisplayName(toRemove[i].getJid()));            
            if (i < toRemove.length - 1) listBuffer.append(", ");
        }
        

        list.setText("Removing " + listBuffer.toString());
        
        DialogDescriptor desc = new DialogDescriptor(this, "Removing ...", true,
            new Object[] {cancelButton}, cancelButton,
            DialogDescriptor.BOTTOM_ALIGN, null, listener);
        
        d = DialogDisplayer.getDefault().createDialog(desc);
        d.addWindowListener(listener);

        result = manager.getContactList().removeContacts(toRemove, listener);
        d.show();
    }

    private class Lst extends WindowAdapter implements ActionListener, Result.Callback, Runnable {
        boolean done;
        
        // cancel
        public void actionPerformed(java.awt.event.ActionEvent e) {
            result.cancel();
        }
        
        // result came, replan to AWT
        public void resultFinished(Result result) {
            done = true;
            SwingUtilities.invokeLater(this);
        }    
        
        // either finished removing or cancelled
        public void run() {
            d.dispose();
        }
        
        public void windowClosed(java.awt.event.WindowEvent e) {
            if (!done) {
                done = true;
                result.cancel();
                d.removeWindowListener(this); // necessary?
            }
        }

        
    }
    
}
