#!/bin/bash
#
# The contents of this file are subject to the terms of the Common Development
# and Distribution License (the License). You may not use this file except in
# compliance with the License.
#
# You can obtain a copy of the License at http://www.netbeans.org/cddl.html
# or http://www.netbeans.org/cddl.txt.
#
# When distributing Covered Code, include this CDDL Header Notice in each file
# and include the License file at http://www.netbeans.org/cddl.txt.
# If applicable, add the following below the CDDL Header, with the fields
# enclosed by brackets [] replaced by your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"
#
# The Original Software is the DocSup module.
# The Initial Developer of the Original Software is Jan Lahoda.
# Portions created by Jan Lahoda_ are Copyright (C) 2002,2003.
# All Rights Reserved.
#
# Contributor(s): Jan Lahoda.
#
find . -type f -name '*.java' -or -name '*.properties' >check-license-files

for file in `cat check-license-files`; do
    if grep <$file "Sun Public" >/dev/null; then
	echo >/dev/null;
    else
        if echo $file | grep results/testrun >/dev/null; then
	    echo >/dev/null;
        else
            if echo $file | grep test/work/sys >/dev/null; then
	        echo >/dev/null;
            else
                echo "No licence in $file";
	    fi;
        fi;
    fi;
done

