/*
 *                 Sun Public License Notice
 *
 * The contents of this file are subject to the Sun Public License
 * Version 1.0 (the "License"). You may not use this file except in
 * compliance with the License. A copy of the License is available at
 * http://www.sun.com/
 *
 * The Original Code is NetBeans. The Initial Developer of the Original
 * Code is Sun Microsystems, Inc. Portions Copyright 1997-2000 Sun
 * Microsystems, Inc. All Rights Reserved.
 */


package org.netbeans.modules.vcscore.ui;

/**
 *@author Milos Kleint
 */

import javax.swing.*;

public class VerifyGroupPanel extends javax.swing.JPanel {

    /** Creates new form VerifyGroupPanel */
    public VerifyGroupPanel() {
        initComponents();
        setPreferredSize(new java.awt.Dimension(450, 450));
        setMinimumSize(new java.awt.Dimension(350, 300));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        lblResult = new javax.swing.JLabel();
        tblResults = new javax.swing.JTabbedPane();

        setLayout(new java.awt.GridBagLayout());

        lblResult.setText("jLabel1");
        lblResult.setLabelFor(tblResults);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 11);
        add(lblResult, gridBagConstraints);

        tblResults.setMinimumSize(new java.awt.Dimension(200, 100));
        tblResults.setPreferredSize(new java.awt.Dimension(200, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.9;
        gridBagConstraints.weighty = 0.9;
        gridBagConstraints.insets = new java.awt.Insets(2, 12, 11, 11);
        add(tblResults, gridBagConstraints);

    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblResult;
    private javax.swing.JTabbedPane tblResults;
    // End of variables declaration//GEN-END:variables

    private static final long serialVersionUID = -8256202642460496022L;    

    
    public void addPanel(JPanel panel, String title) {
        tblResults.add(title, panel);
    }
    
    public void setDescription(String desc) {
        lblResult.setText(desc);
        tblResults.getAccessibleContext().setAccessibleName(desc);
        tblResults.getAccessibleContext().setAccessibleDescription(desc);
        this.getAccessibleContext().setAccessibleDescription(desc);        
    }
}
