/*
 *                 Sun Public License Notice
 * 
 * The contents of this file are subject to the Sun Public License
 * Version 1.0 (the "License"). You may not use this file except in
 * compliance with the License. A copy of the License is available at
 * http://www.sun.com/
 * 
 * The Original Code is NetBeans. The Initial Developer of the Original
 * Code is Sun Microsystems, Inc. Portions Copyright 1997-2004 Sun
 * Microsystems, Inc. All Rights Reserved.
 */

package org.netbeans.modules.j2ee.blueprints.ui;

import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Rectangle2D;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.Iterator;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.Set;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.border.EmptyBorder;
import javax.swing.text.BadLocationException;
import javax.swing.text.html.HTMLEditorKit;
import org.netbeans.modules.j2ee.blueprints.catalog.SolutionsCatalog;
import org.netbeans.modules.j2ee.blueprints.catalog.demoxmlparser.Category;
import org.netbeans.modules.j2ee.blueprints.catalog.demoxmlparser.Demo;
import org.netbeans.modules.j2ee.blueprints.catalog.demoxmlparser.Example;
import org.openide.ErrorManager;
import org.openide.awt.HtmlBrowser;
import org.openide.filesystems.FileUtil;
import org.openide.util.NbBundle;
import org.openide.filesystems.FileObject;
import org.openide.loaders.DataObject;
import org.openide.filesystems.Repository;
import org.openide.cookies.InstanceCookie;
import javax.swing.Action;


/**
 * Browser for BluePrints Solutions Catalog Entries.
 *
 * The user can browse categories and articles, design documents and
 * launch a wizard to create new projects from a template.
 *
 * @author Mark Roth
 * @author Yutaka Yoshida
 * @author Ludo
 * @author Richard Gregor
 */
public class BluePrintsPanel extends javax.swing.JPanel {
    private static final String UI_RESOURCES_URL = 
        "/org/netbeans/modules/j2ee/blueprints/ui/resources"; // NOI18N
    private static final String ICON_CATEGORY = 
        UI_RESOURCES_URL + "/category.gif"; // NOI18N
    private static final String ICON_ARTICLE = 
        UI_RESOURCES_URL + "/article.gif"; // NOI18N
    private static ResourceBundle bundle = ResourceBundle.getBundle(
        "org/netbeans/modules/j2ee/blueprints/ui/Bundle"); // NOI18N
    private static final String CATALOG_RESOURCES_URL = 
        "/org/netbeans/modules/j2ee/blueprints/catalog/resources"; // NOI18N
    
    private HtmlBrowser.URLDisplayer displayer = HtmlBrowser.URLDisplayer.getDefault();
    private static final String OPEN_SAMPLE_ACTION = 
        "org-netbeans-modules-project-ui-WelcomeScreenHack/" + // NOI18N
        "org-netbeans-modules-project-ui-NewSample.instance";  // NOI18N
    private URL url;
    private SolutionsCatalog solutionsCatalog = SolutionsCatalog.getInstance();
   
    /** Creates new form TitlePanel */
    public BluePrintsPanel() {
        initComponents();
        TABS.put(TAB_CATEGORY, categoryScroll);
        TABS.put(TAB_SOLUTION, solutionBrowser);
        TABS.put(TAB_DESIGN, designBrowser);
        TABS.put(TAB_EXAMPLE, examplePnl);
        tabbedPnl.removeAll();
        initComboBox();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPopupMenu1 = new javax.swing.JPopupMenu();
        titlePanel = new javax.swing.JPanel();
        sunLogoLbl = new javax.swing.JLabel();
        titleSubPnl = new javax.swing.JPanel();
        titleLbl = new AntialiasedJLabel();
        titleSubLbl = new AntialiasedJLabel();
        toolbarPanel = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        forwardBtn = new javax.swing.JButton();
        entryCbx = new javax.swing.JComboBox();
        tabbedPnl = new javax.swing.JTabbedPane();
        categoryScroll = new javax.swing.JScrollPane();
        categoryText = new javax.swing.JTextPane();
        solutionBrowser = new HtmlBrowser(false, false);
        designBrowser = new HtmlBrowser(false, false);
        examplePnl = new javax.swing.JPanel();
        launchExampleText = new javax.swing.JTextPane();
        installBtn = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        setBackground(new java.awt.Color(255, 255, 255));
        titlePanel.setLayout(new java.awt.GridBagLayout());

        titlePanel.setOpaque(false);
        sunLogoLbl.setBackground(new java.awt.Color(89, 79, 191));
        sunLogoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/netbeans/modules/j2ee/blueprints/ui/resources/logo_sun.gif")));
        sunLogoLbl.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        titlePanel.add(sunLogoLbl, gridBagConstraints);

        titleSubPnl.setLayout(new java.awt.GridBagLayout());

        titleLbl.setBackground(new java.awt.Color(251, 226, 73));
        titleLbl.setFont(new java.awt.Font("Dialog", 1, 24));
        titleLbl.setForeground(new java.awt.Color(89, 79, 191));
        titleLbl.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/j2ee/blueprints/ui/Bundle").getString("NB_title"));
        titleLbl.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 12, 1, 1)));
        titleLbl.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        titleSubPnl.add(titleLbl, gridBagConstraints);

        titleSubLbl.setBackground(new java.awt.Color(251, 226, 73));
        titleSubLbl.setForeground(new java.awt.Color(89, 79, 191));
        titleSubLbl.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/j2ee/blueprints/ui/Bundle").getString("NB_subtitle"));
        titleSubLbl.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 12, 1, 1)));
        titleSubLbl.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        titleSubPnl.add(titleSubLbl, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        titlePanel.add(titleSubPnl, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 7, 12);
        add(titlePanel, gridBagConstraints);

        toolbarPanel.setLayout(new java.awt.GridBagLayout());

        toolbarPanel.setOpaque(false);
        backBtn.setFont(new java.awt.Font("Dialog", 0, 12));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/netbeans/modules/j2ee/blueprints/ui/resources/back.gif")));
        backBtn.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/j2ee/blueprints/ui/Bundle").getString("backBtn"));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        toolbarPanel.add(backBtn, gridBagConstraints);

        forwardBtn.setFont(new java.awt.Font("Dialog", 0, 12));
        forwardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/netbeans/modules/j2ee/blueprints/ui/resources/forward.gif")));
        forwardBtn.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/j2ee/blueprints/ui/Bundle").getString("forwardBtn"));
        forwardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forwardBtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        toolbarPanel.add(forwardBtn, gridBagConstraints);

        entryCbx.setFont(new java.awt.Font("Dialog", 0, 12));
        entryCbx.setMaximumRowCount(16);
        entryCbx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                entryCbxItemStateChanged(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        toolbarPanel.add(entryCbx, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 1, 7);
        add(toolbarPanel, gridBagConstraints);

        tabbedPnl.setFont(new java.awt.Font("Dialog", 0, 12));
        categoryText.setEditable(false);
        categoryText.setEditorKit(new HTMLEditorKit());
        categoryText.setMargin(new java.awt.Insets(12, 12, 12, 12));
        categoryScroll.setViewportView(categoryText);

        tabbedPnl.addTab(java.util.ResourceBundle.getBundle("org/netbeans/modules/j2ee/blueprints/ui/Bundle").getString("categoryPnl"), categoryScroll);

        tabbedPnl.addTab(java.util.ResourceBundle.getBundle("org/netbeans/modules/j2ee/blueprints/ui/Bundle").getString("solutionPnl"), solutionBrowser);

        tabbedPnl.addTab(java.util.ResourceBundle.getBundle("org/netbeans/modules/j2ee/blueprints/ui/Bundle").getString("designPnl"), designBrowser);

        examplePnl.setLayout(new java.awt.GridBagLayout());

        examplePnl.setBackground(new java.awt.Color(255, 255, 255));
        launchExampleText.setEditable(false);
        launchExampleText.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/j2ee/blueprints/ui/Bundle").getString("launchExampleText"));
        launchExampleText.setEnabled(false);
        launchExampleText.setMargin(new java.awt.Insets(12, 12, 12, 12));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 7, 0);
        examplePnl.add(launchExampleText, gridBagConstraints);

        installBtn.setFont(new java.awt.Font("Dialog", 0, 12));
        installBtn.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/j2ee/blueprints/ui/Bundle").getString("launchBtn"));
        installBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                installBtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        examplePnl.add(installBtn, gridBagConstraints);

        tabbedPnl.addTab(java.util.ResourceBundle.getBundle("org/netbeans/modules/j2ee/blueprints/ui/Bundle").getString("examplePnl"), examplePnl);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 12, 12);
        add(tabbedPnl, gridBagConstraints);

    }//GEN-END:initComponents

    private void forwardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardBtnActionPerformed
        goForward();
    }//GEN-LAST:event_forwardBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        goBack();
    }//GEN-LAST:event_backBtnActionPerformed

    private void entryCbxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_entryCbxItemStateChanged
        if(!navigating) {
            if(lastSelectedIndex != entryCbx.getSelectedIndex()) {
                // sometimes Swing calls this twice - only select the new
                // entry if a new entry was selected.
                lastSelectedIndex = entryCbx.getSelectedIndex();
                selectNewEntry();
            }
        }
    }//GEN-LAST:event_entryCbxItemStateChanged

    private void installBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_installBtnActionPerformed
        installExample();
    }//GEN-LAST:event_installBtnActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane categoryScroll;
    private javax.swing.JTextPane categoryText;
    private javax.swing.JPanel designBrowser;
    private javax.swing.JComboBox entryCbx;
    private javax.swing.JPanel examplePnl;
    private javax.swing.JButton forwardBtn;
    private javax.swing.JButton installBtn;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextPane launchExampleText;
    private javax.swing.JPanel solutionBrowser;
    private javax.swing.JLabel sunLogoLbl;
    private javax.swing.JTabbedPane tabbedPnl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JLabel titleSubLbl;
    private javax.swing.JPanel titleSubPnl;
    private javax.swing.JPanel toolbarPanel;
    // End of variables declaration//GEN-END:variables

    private BrowseHistory history = new BrowseHistory();
    private BrowseHistoryToken historyToken = new BrowseHistoryToken();
    
    public static final String TAB_CATEGORY = "categoryPnl"; // NOI18N
    public static final String TAB_SOLUTION = "solutionPnl"; // NOI18N
    public static final String TAB_DESIGN   = "designPnl";   // NOI18N
    public static final String TAB_EXAMPLE  = "examplePnl";  // NOI18N
    public final HashMap TABS = new HashMap();
    
    // True if a change in the combo box should not trigger events.
    private boolean navigating = false;
    private int lastSelectedIndex = -1;
    private Timer scrollTimer = null;

    // Special constants that allow us to preselect a template in the new 
    // project wizard
    private static final String BUNDLE_PROPERTY_PREFIX = 
        "Blueprints"; // NOI18N
    private static final String PRESELECT_CATEGORY = 
        "PRESELECT_CATEGORY"; // NOI18N
    private static final String PRESELECT_TEMPLATE =
        "PRESELECT_TEMPLATE"; // NOI18N

    public Category getSelectedCategory() {
        Object entry = entryCbx.getSelectedItem();
        if(!(entry instanceof Category)) {
            // Scan up the list until we hit a category
            int index = entryCbx.getSelectedIndex();
            do {
                index--;
                entry = entryCbx.getItemAt(index);
            } while((index > 0) && !(entry instanceof Category));
        }
        return (Category)entry;
    }
    
    public Example getSelectedArticle() {
        Object entry = entryCbx.getSelectedItem();
        return (entry instanceof Example) ? (Example)entry : null;
    }
    
    private void initComboBox() {
        // Set up combo boxes:
        entryCbx.setRenderer(new EntryListCellRenderer());
        entryCbx.setModel(new EntryComboBoxModel());
        entryCbx.setSelectedIndex(0);
        history.clear();
        updateTabs();
        updateButtons();
        historyToken = createBrowseHistoryToken();
    }
    
    private void selectNewEntry() {
        // Article and category will be set in the current history token
        // but scroll position and tab may be out of date.  Update them.
        historyToken.setScrollPosition(getScrollPosition());
        historyToken.setTab(getSelectedTabName());
        history.pushBackStack(historyToken);
                
        updateTabs();
        updateButtons();
        
        // Create a new token that contains the new article and category.
        historyToken = createBrowseHistoryToken();
    }

    private void goForward() {
        if(!history.isForwardStackEmpty()) {
            navigateTo(history.forward(createBrowseHistoryToken()));
            updateButtons();
        }
    }
    
    private void goBack() {
        if(!history.isBackStackEmpty()) {
            navigateTo(history.back(createBrowseHistoryToken()));
            updateButtons();
        }
    }
    
    private BrowseHistoryToken createBrowseHistoryToken() {
        String category = getSelectedCategory().getId(0);
        Example example = getSelectedArticle();
        String article = (example == null) ? null : example.getId(0);
        String tab = getSelectedTabName();
        int scrollPosition = getScrollPosition();
        return new BrowseHistoryToken(category, article, tab, scrollPosition);
    }
    
    private String getSelectedTabName() {
        Component selectedTab = tabbedPnl.getSelectedComponent();
        String result = null;
        Set entries = TABS.entrySet();
        Iterator iter = entries.iterator();
        while(iter.hasNext()) {
            Map.Entry entry = (Map.Entry)iter.next();
            if(entry.getValue() == selectedTab) {
                result = (String)entry.getKey();
            }
        }
        return result;
    }
    
    private int getScrollPosition() {
        int result = 0;
        Component selectedTab = tabbedPnl.getSelectedComponent();
        if(selectedTab == categoryScroll) {
            result = categoryScroll.getVerticalScrollBar().getValue();
        }
        else if(selectedTab == solutionBrowser) {
            result = getBrowserScrollPosition((HtmlBrowser)solutionBrowser);
        }
        else if(selectedTab == designBrowser) {
            result = getBrowserScrollPosition((HtmlBrowser)designBrowser);
        }
        else if(selectedTab == examplePnl) {
            result = 0;
        }
        return result;
    }
    
    private void scrollTo(final int position) {
        // It takes a bit for the page to load.  This timer will periodically
        // check if enough of the page has loaded that we can scroll to the
        // desired position.
        if(this.scrollTimer != null) {
            this.scrollTimer.stop();
        }
        this.scrollTimer = new Timer(100,
            new ActionListener() {
                int timeout = 50;
                public void actionPerformed(ActionEvent e) {
                    boolean done = false;
                    Component selectedTab = tabbedPnl.getSelectedComponent();
                    if(selectedTab == categoryScroll) {
                        categoryScroll.getVerticalScrollBar().setValue(
                            position);
                        done = true;
                    }
                    else if(selectedTab == solutionBrowser) {
                        done = setBrowserScrollPosition(
                            (HtmlBrowser)solutionBrowser, position);
                    }
                    else if(selectedTab == designBrowser) {
                        done = setBrowserScrollPosition(
                            (HtmlBrowser)designBrowser, position);
                    }
                    else if(selectedTab == examplePnl) {
                        // cannot scroll this tab
                        done = true;
                    }
                    timeout--;
                    if(timeout <= 0) done = true;
                    if(done) {
                        scrollTimer.stop();
                        scrollTimer = null;
                    }
                }
            }
        );
        this.scrollTimer.start();
    }
    
    private int getBrowserScrollPosition(HtmlBrowser browser) {
        int result = 0;
        // If this browser has a scroll pane, use it to determine
        // the current position.
        Component c = browser.getComponent(0);
        if(c instanceof JScrollPane) {
            JScrollPane pane = (JScrollPane)c;
            result = pane.getVerticalScrollBar().getValue();
        }
        return result;
    }
    
    private boolean setBrowserScrollPosition(HtmlBrowser browser, 
        int position) 
    {
        boolean result = false;
        // If this browser has a scroll pane, use it to set
        // the current position.
        Component c = browser.getComponent(0);
        if(c instanceof JScrollPane) {
            JScrollPane pane = (JScrollPane)c;
            JScrollBar bar = pane.getVerticalScrollBar();
            if(position <= bar.getMaximum()) {
                bar.setValue(position);
                result = true;
            }
        }
        return result;
    }
    
    private void navigateTo(BrowseHistoryToken token) {
        if(token != null) {
            String category = token.getCategory();
            String article = token.getArticle();
            navigateTo(category, article);
            updateTabs();
            String tab = token.getTab();
            selectTab(tab);
            int scrollPosition = token.getScrollPosition();
            scrollTo(scrollPosition);
            historyToken = createBrowseHistoryToken();
        }
    }
    
    private void navigateTo(String category, String article) {
        navigating = true;  // prevent duplicate events
        if(category != null) {
            boolean foundCategory = false;
            int count = entryCbx.getItemCount();
            for(int i = 0; i < count; i++) {
                Object entry = entryCbx.getItemAt(i);
                if(entry instanceof Category) {
                    Category c = (Category)entry;
                    if(c.getId(0).equals(category)) {
                        foundCategory = true;
                        if(article == null) {
                            // Select just this category
                            entryCbx.setSelectedIndex(i);
                            break;
                        }
                    }
                    else {
                        if(foundCategory) {
                            // We found the category but not the article.
                            break;
                        }
                    }
                }
                else {
                    if(foundCategory) {
                        Example e = (Example)entryCbx.getItemAt(i);
                        if(e.getId(0).equals(article)) {
                            // Select this article
                            entryCbx.setSelectedIndex(i);
                            break;
                        }
                    }
                }
            }
        }
        navigating = false;
    }
    
    private void updateButtons() {
        backBtn.setEnabled(!history.isBackStackEmpty());
        forwardBtn.setEnabled(!history.isForwardStackEmpty());
    }
    
    private void updateTabs() {
        Category category = getSelectedCategory();
        Example example = getSelectedArticle();

        // Ensure the category panel is visible when no example is selected
        // and the other panels are visible when an example is selected.
        if(example == null) {
            tabbedPnl.removeAll();
            tabbedPnl.addTab(bundle.getString(TAB_CATEGORY), categoryScroll); 
        }
        else {
            tabbedPnl.removeAll();
            tabbedPnl.addTab(bundle.getString(TAB_SOLUTION), solutionBrowser); 
            tabbedPnl.addTab(bundle.getString(TAB_DESIGN), designBrowser);
            tabbedPnl.addTab(bundle.getString(TAB_EXAMPLE), examplePnl);   
        }
        
        updateCategoryTab();
        updateSolutionTab();
        updateDesignTab();
        updateExamplesTab();
    }
    
    private void selectTab(String tab) {
        tabbedPnl.setSelectedComponent((Component)TABS.get(tab));
    }
    
    private void updateCategoryTab() {
        Category category = getSelectedCategory();
        Example example = getSelectedArticle();
        if(example == null) {
            categoryText.setText(
                "<h1><font face=\"Dialog\">" + category.getName(0) // NOI18N
                + "</font></h1>" + "<font face=\"Dialog\">"        // NOI18N
                + category.getDescription(0) + "</font>"           // NOI18N
            );
        }
    }
    
    private void updateSolutionTab() {
        Category category = getSelectedCategory();
        Example example = getSelectedArticle();
        if(example != null) {
            String articleURLString = CATALOG_RESOURCES_URL 
                + "/web/" + example.getDoc(0); // NOI18N
            URL articleURL = getClass().getResource(articleURLString);
            ((HtmlBrowser)solutionBrowser).setURL(articleURL);
        }
    }
    
    private void updateDesignTab() {
        Category category = getSelectedCategory();
        Example example = getSelectedArticle();
        if(example != null) {
            if(example.getDesigndoc().length == 0) {
                tabbedPnl.remove(designBrowser);
            }
            else {
                String designURLString = CATALOG_RESOURCES_URL
                    + "/web/" + example.getDesigndoc(0); // NOI18N
                URL designURL = getClass().getResource(designURLString);
                ((HtmlBrowser)designBrowser).setURL(designURL);
            }
        }
    }
    
    private void updateExamplesTab() {
        Category category = getSelectedCategory();
        Example example = getSelectedArticle();
        String examplePath = getExamplePath();
        if(example != null) {
            if(examplePath == null) {
                tabbedPnl.remove(examplePnl);
            }
        }
    }
    
    private void installExample() {
        performAction(OPEN_SAMPLE_ACTION, "");
    }
    
    private String getExamplePath() {
        String result = null;
        Example example = getSelectedArticle();
        if(example != null) {
            // Guess the name of the zip from the <path> element
            // (not always accurate, but this is the best we can do)
            String[] paths = example.getPath();
            if(paths.length > 0) {
                result = paths[0];
                if(result.indexOf('.') != -1) {
                    // there's a filename in the path. Strip it.
                    result = result.substring(0, result.lastIndexOf('/'));
                }
                if(result.indexOf('/') != -1) {
                    // Strip all slashes before the example path
                    result = result.substring(result.lastIndexOf('/') + 1);
                }
            }
        }
        return result;
    }
    
    private void showURL(String s) {
        URL url;
        try {
            url = new URL(NbBundle.getMessage(getClass(),s));
            displayer.showURL(url);
        } catch (java.net.MalformedURLException ex) {
            ErrorManager.getDefault().notify(ex);
        }
    }
    
    private Action findAction (String key) {
        FileObject fo = 
            Repository.getDefault().getDefaultFileSystem().findResource(key);
        
        if (fo != null && fo.isValid()) {
            try {
                DataObject dob = DataObject.find (fo);
                InstanceCookie ic = 
                    (InstanceCookie) dob.getCookie(InstanceCookie.class);
                
                if (ic != null) {
                    Object instance = ic.instanceCreate();
                    if (instance instanceof Action) {
                        return (Action) instance;
                    }
                }
            } catch (Exception e) {
                ErrorManager.getDefault().notify(ErrorManager.WARNING, e);
                return null;
            }
        }
        return null;
    }
    
    private boolean performAction(String key, String command) {
        Action a = findAction (key);
        if (a == null) {
            return false;
        }
        a.putValue(PRESELECT_CATEGORY, BUNDLE_PROPERTY_PREFIX + "/" // NOI18N
            + getSelectedCategory().getId(0));
        a.putValue(PRESELECT_TEMPLATE, getExamplePath());
        ActionEvent ae = new ActionEvent(this, ActionEvent.ACTION_PERFORMED, 
            command);
        try {
            a.actionPerformed(ae);
            return true;
        } catch (Exception e) {
            ErrorManager.getDefault().notify(ErrorManager.WARNING, e);
            return false;
        }
    }
    
    /**
     * Backing model for the entry drop-down.
     * Gets its data from demo.xml.
     */
    private class EntryComboBoxModel
        extends DefaultComboBoxModel
    {
        private Demo demo;
        private ArrayList entries = new ArrayList();
        
        public EntryComboBoxModel() {
            this.demo = solutionsCatalog.getDemoXml();
            Category[] categories = demo.getCategory();
            for(int categoryNum = 0; categoryNum < categories.length; 
                categoryNum++) 
            {
                entries.add(categories[categoryNum]);
                Example[] examples = categories[categoryNum].getExample();
                for(int exampleNum = 0; exampleNum < examples.length; 
                    exampleNum++) 
                {
                    entries.add(examples[exampleNum]);
                }
            }
        }
        
        public int getSize() {
            return entries.size();
        }
        
        public Object getElementAt(int index) {
            return entries.get(index);
        }
    }
    
    /**
     * Cell renderer for the entry drop-down
     *
     * Adds an icon and changes the text of the cell to match the name of
     * the category or article.
     */
    private static class EntryListCellRenderer 
        extends DefaultListCellRenderer
    {
        private ImageIcon categoryIcon;
        private ImageIcon articleIcon;

        public EntryListCellRenderer() {
            this.categoryIcon = new ImageIcon(getClass().getResource(
                ICON_CATEGORY));
            this.articleIcon = new ImageIcon(getClass().getResource(
                ICON_ARTICLE));
        }

        public Component getListCellRendererComponent(JList list,
            Object value, int index, boolean isSelected, boolean cellHasFocus)
        {
            Component result = super.getListCellRendererComponent(list, value,
                index, isSelected, cellHasFocus);
            JLabel label = (JLabel)result;
            if(value instanceof Category) {
                Category category = (Category)value;
                label.setIcon(categoryIcon);
                label.setText(category.getName(0));
            }
            else if(value instanceof Example) {
                Example example = (Example)value;
                label.setIcon(articleIcon);
                label.setText(example.getName(0));
                // Tab the articles so they look like they're in the category
                label.setBorder(new EmptyBorder(0, 19, 0, 0));
            }
            return result;
        }
    }
}


