/*
 *                 Sun Public License Notice
 * 
 * The contents of this file are subject to the Sun Public License
 * Version 1.0 (the "License"). You may not use this file except in
 * compliance with the License. A copy of the License is available at
 * http://www.sun.com/
 * 
 * The Original Code is NetBeans. The Initial Developer of the Original
 * Code is Sun Microsystems, Inc. Portions Copyright 1997-2001 Sun
 * Microsystems, Inc. All Rights Reserved.
 */

package org.netbeans.modules.vcs.advanced.wizard.mount;

import org.openide.loaders.TemplateWizard;

/**
 *
 * @author  Martin Entlicher
 */
public class ProfilePanelUI extends javax.swing.JPanel {

    private boolean initialized = false;
    
    MountWizardData data;
    
    private static final long serialVersionUID = 1184058637535734526L;
    
    /** Creates new form ProfilePanel */
    public ProfilePanelUI(int index, MountWizardData data) {
        initComponents();
        if (index == 0) {
            setName(org.openide.util.NbBundle.getMessage(ProfilePanelUI.class, "CTL_ProfilePanel"));
        } else {
            setName(data.getProfileLabel(index));
        }
        getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(ProfilePanelUI.class, "ACS_ProfilePanelA11yName"));  // NOI18N
        getAccessibleContext().setAccessibleDescription(org.openide.util.NbBundle.getMessage(ProfilePanelUI.class, "ACS_ProfilePanelA11yDesc"));  // NOI18N
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new java.awt.BorderLayout());

    }//GEN-END:initComponents

    public void addNotify() {
        super.addNotify();
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                java.awt.Container c = getTopLevelAncestor();
                if (c instanceof java.awt.Window) {
                    ((java.awt.Window) c).pack();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
