/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 1997-2007 Sun Microsystems, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. You can obtain a copy of the License at
 * http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  When distributing the software, include this License Header
 * Notice in each file and include the License file at
 * nbbuild/licenses/CDDL-GPL-2-CP.  Sun designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Sun in the GPL Version 2 section of the License file that
 * accompanied this code. If applicable, add the following below the
 * License Header, with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * Contributor(s):
 *
 * The Original Software is NetBeans. The Initial Developer of the Original
 * Software is Sun Microsystems, Inc. Portions Copyright 1997-2006 Sun
 * Microsystems, Inc. All Rights Reserved.
 *
 * If you wish your version of this file to be governed by only the CDDL
 * or only the GPL Version 2, indicate your decision by adding
 * "[Contributor] elects to include this software in this distribution
 * under the [CDDL or GPL Version 2] license." If you do not indicate a
 * single choice of license, a recipient has the option to distribute
 * your version of this file under either the CDDL, the GPL Version 2 or
 * to extend the choice of license to its licensees as provided above.
 * However, if you add GPL Version 2 code and therefore, elected the GPL
 * Version 2 license, then the option applies only if the new code is
 * made subject to such option by the copyright holder.
 */

/*
 * BindingContextPanel.java
 *
 * Created on July 22, 1999, 9:31 PM
 */





package org.netbeans.modules.corba.browser.ns;

import javax.swing.JFileChooser;
import org.openide.util.NbBundle;
import org.netbeans.modules.corba.utils.IORFileFilter;

/**
 *
 * @author  jformanek, Tomas Zezula
 * @version
 */

public class BindingContextPanel extends javax.swing.JPanel implements java.awt.event.ItemListener {

    private static final String FILE_PROTOCOL = "file:///";     // NOI18N

    static final long serialVersionUID =8322471659336275904L;
    /** Creates new form BindingContextPanel */
    
    public BindingContextPanel() {
        
        initComponents();
        this.jRadioButton1.addItemListener(this);
        this.jRadioButton2.addItemListener(this);
        this.jRadioButton1.setSelected(true);
        java.util.ResourceBundle b = org.openide.util.NbBundle.getBundle("org/netbeans/modules/corba/browser/ns/Bundle"); //NOI18N
        nameLabel.setDisplayedMnemonic(b.getString("CTL_LabelName_MNE").charAt(0));    //NOI18N
        urlLabel.setDisplayedMnemonic(b.getString("CTL_LabelURL_MNE").charAt(0));      //NOI18N
        kindLabel.setDisplayedMnemonic(b.getString("CTL_LabelKind_MNE").charAt(0));    //NOI18N
        iorLabel.setDisplayedMnemonic(b.getString("CTL_LabelIOR_MNE").charAt(0));      //NOI18N
        this.getAccessibleContext().setAccessibleDescription(b.getString("AD_BindingContextPanel"));
        nameField.getAccessibleContext().setAccessibleDescription(b.getString("AD_LabelName"));
        iorField.getAccessibleContext().setAccessibleDescription(b.getString("AD_LabelURL"));
        kindField.getAccessibleContext().setAccessibleDescription(b.getString("AD_LabelKind"));
        urlField.getAccessibleContext().setAccessibleDescription(b.getString("AD_LabelIOR"));
        this.browse.getAccessibleContext () .setAccessibleDescription ("AD_Browse");
        this.jRadioButton1.getAccessibleContext ().setAccessibleDescription (b.getString ("AD_FromURL"));
        this.jRadioButton2.getAccessibleContext ().setAccessibleDescription (b.getString ("AD_FromIOR"));
        this.browse.setMnemonic (b.getString ("TXT_Browse_MNE").charAt (0));
        this.jRadioButton1.setMnemonic (b.getString ("TXT_FromURL_MNE").charAt (0));
        this.jRadioButton2.setMnemonic (b.getString ("TXT_FromIOR_MNE").charAt (0));
        
    }
    
    
    /** This method is called from within the constructor to
     *
     * initialize the form.
     *
     * WARNING: Do NOT modify this code. The content of this method is
     *
     * always regenerated by the FormEditor.
     *
     */
    
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        kindLabel = new javax.swing.JLabel();
        kindField = new javax.swing.JTextField();
        urlLabel = new javax.swing.JLabel();
        urlField = new javax.swing.JTextField();
        iorLabel = new javax.swing.JLabel();
        iorField = new javax.swing.JTextField();
        fillPanel = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        browse = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        setPreferredSize(new java.awt.Dimension(400, 260));
        nameLabel.setLabelFor(nameField);
        nameLabel.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/corba/browser/ns/Bundle").getString("CTL_LabelName"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        add(nameLabel, gridBagConstraints);

        nameField.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(12, 10, 0, 11);
        add(nameField, gridBagConstraints);

        kindLabel.setLabelFor(kindField);
        kindLabel.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/corba/browser/ns/Bundle").getString("CTL_LabelKind"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 0, 0);
        add(kindLabel, gridBagConstraints);

        kindField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kindFieldActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 11);
        add(kindField, gridBagConstraints);

        urlLabel.setLabelFor(urlField);
        urlLabel.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/corba/browser/ns/Bundle").getString("CTL_LabelURL"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 0, 0);
        add(urlLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 11);
        add(urlField, gridBagConstraints);

        iorLabel.setLabelFor(iorField);
        iorLabel.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/corba/browser/ns/Bundle").getString("CTL_LabelIOR"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 0, 0);
        add(iorLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 11);
        add(iorField, gridBagConstraints);

        fillPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        fillPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        add(fillPanel, gridBagConstraints);

        jRadioButton1.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/corba/browser/ns/Bundle").getString("TXT_FromURL"));
        buttonGroup1.add(jRadioButton1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 12);
        add(jRadioButton1, gridBagConstraints);

        jRadioButton2.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/corba/browser/ns/Bundle").getString("TXT_FromIOR"));
        buttonGroup1.add(jRadioButton2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 12);
        add(jRadioButton2, gridBagConstraints);

        browse.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/corba/browser/ns/Bundle").getString("TXT_Browse"));
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browse(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 12);
        add(browse, gridBagConstraints);

    }//GEN-END:initComponents

    private void browse(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browse
        // Add your handling code here:
        JFileChooser fs = new JFileChooser ();
        fs.setFileFilter (new IORFileFilter ());
        if (fs.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            java.io.File file = fs.getSelectedFile();
            if (file != null) {
                this.urlField.setText (FILE_PROTOCOL + file.getAbsolutePath ());
            }
        }
    }//GEN-LAST:event_browse
    
    private void kindFieldActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kindFieldActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_kindFieldActionPerformed
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField iorField;
    private javax.swing.JTextField urlField;
    private javax.swing.JButton browse;
    private javax.swing.JLabel iorLabel;
    private javax.swing.JTextField kindField;
    private javax.swing.JLabel urlLabel;
    private javax.swing.JPanel fillPanel;
    private javax.swing.JLabel kindLabel;
    // End of variables declaration//GEN-END:variables
    
    
    
    public String getName() {
        
        return nameField.getText();
        
    }
    
    
    public String getKind() {
        
        return kindField.getText();
        
    }
    
    
    public String getUrl() {
        
        return urlField.getText();
        
    }
    
    
    public String getIOR() {
        return iorField.getText();
        
    }
    
    public void itemStateChanged (java.awt.event.ItemEvent event) {
        boolean flag = this.jRadioButton1.isSelected ();
        this.urlLabel.setEnabled (flag);
        this.urlField.setEnabled (flag);
        this.browse.setEnabled (flag);
        this.iorLabel.setEnabled (!flag);
        this.iorField.setEnabled (!flag);
    }
    
}

