/*
 *                 Sun Public License Notice
 * 
 * The contents of this file are subject to the Sun Public License
 * Version 1.0 (the "License"). You may not use this file except in
 * compliance with the License. A copy of the License is available at
 * http://www.sun.com/
 * 
 * The Original Code is NetBeans. The Initial Developer of the Original
 * Code is Sun Microsystems, Inc. Portions Copyright 1997-2001 Sun
 * Microsystems, Inc. All Rights Reserved.
 */

/*
 * StartPanel.java
 *
 * Created on 12. øíjen 2000, 9:52
 */

package org.netbeans.modules.corba.browser.ns;

/**
 *
 * @author  Tomas Zezula
 * @version 
 */
public class StartPanel extends javax.swing.JPanel {

    /** Creates new form StartPanel */
    public StartPanel() {
        initComponents ();
        postInitComponents();
        
        java.util.ResourceBundle b = org.openide.util.NbBundle.getBundle("org.netbeans.modules.corba.browser.ns.Bundle"); //NOI18N
        jLabel1.setDisplayedMnemonic(b.getString("CTL_Port_MNE").charAt(0)); //NOI18N
        jLabel2.setDisplayedMnemonic(b.getString("CTL_LabelName_MNE").charAt(0)); //NOI18N
        jLabel3.setDisplayedMnemonic(b.getString("CTL_LabelKind_MNE").charAt(0)); //NOI18N
        this.port.getAccessibleContext().setAccessibleDescription (b.getString("AD_Port"));
        this.name.getAccessibleContext().setAccessibleDescription (b.getString("AD_LabelName"));
        this.kind.getAccessibleContext().setAccessibleDescription (b.getString("AD_LabelKind"));
    }
    
    private void postInitComponents () {
        this.port.setText("900");
    }
    
    public short getPort () {
        try {
            return Short.parseShort (this.port.getText());
        }catch (NumberFormatException nfe) {
            return -1;
        }
    }
    
    public void setPort (short port) {
        this.port.setText ( Short.toString (port));
    }
    
    public String getName () {
        return this.name.getText();
    }
    
    public void setName (String name) {
        this.name.setText (name);
    }

    public String getKind () {
        return this.kind.getText();
    }
    
    public void setKind (String kind) {
        this.kind.setText (kind);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        kind = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        port = new javax.swing.JTextField();
        fillPanel = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        jLabel2.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/corba/browser/ns/Bundle").getString("CTL_LabelName"));
        jLabel2.setLabelFor(name);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jLabel2, gridBagConstraints);

        name.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(12, 10, 0, 11);
        gridBagConstraints.weightx = 1.0;
        add(name, gridBagConstraints);

        jLabel3.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/corba/browser/ns/Bundle").getString("CTL_LabelKind"));
        jLabel3.setLabelFor(kind);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 11);
        add(kind, gridBagConstraints);

        jLabel1.setText(java.util.ResourceBundle.getBundle("org/netbeans/modules/corba/browser/ns/Bundle").getString("CTL_Port"));
        jLabel1.setLabelFor(port);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 11);
        gridBagConstraints.weightx = 1.0;
        add(port, gridBagConstraints);

        fillPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        fillPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(fillPanel, gridBagConstraints);

    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField port;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField kind;
    private javax.swing.JPanel fillPanel;
    // End of variables declaration//GEN-END:variables

}
