/*
 *                 Sun Public License Notice
 * 
 * The contents of this file are subject to the Sun Public License
 * Version 1.0 (the "License"). You may not use this file except in
 * compliance with the License. A copy of the License is available at
 * http://www.sun.com/
 * 
 * The Original Code is NetBeans. The Initial Developer of the Original
 * Code is Sun Microsystems, Inc. Portions Copyright 1997-2001 Sun
 * Microsystems, Inc. All Rights Reserved.
 */

package org.netbeans.modules.jndi.gui;

import org.netbeans.modules.jndi.JndiRootNode;
/**
 *
 * @author  tzezula
 * @version 
 */
public class CreateAttributePanel extends javax.swing.JPanel {

    /** Creates new form CreateAttributePanel */
    public CreateAttributePanel() {
        initComponents ();
        this.nameLabel.setDisplayedMnemonic (JndiRootNode.getLocalizedString ("TXT_AttributeName_MNEM").charAt(0));
        this.valueLabel.setDisplayedMnemonic (JndiRootNode.getLocalizedString("TXT_AttributeValue_MNEN").charAt(0));
        this.nameLabel.requestFocus();
        name.getAccessibleContext().setAccessibleDescription (JndiRootNode.getLocalizedString ("AD_AttributeName"));
        value.getAccessibleContext().setAccessibleDescription (JndiRootNode.getLocalizedString("AD_AttributeValue"));
    }

    public void requestFocus () {
        this.name.requestFocus();
    }
    
    public boolean requestDefaultFocus () {
        this.name.requestFocus();
        return true;
    }
    
    /** Returns the name of the Attribute
     *  @return String name
     */
    public String getName(){
        return this.name.getText();
    }

    /** Returns the value of the Attribute
     *  @return String value
     */
    public String getValue(){
        return this.value.getText();
    }

    /** Sets the value of the name field
     *  @param String name
     */
    public void setName (String name){
        this.name.setText(name);
    }

    /** Sets the value of the value field
     *  @param String name
     */
    public void setValue(String value){
        this.value.setText(value);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        nameLabel = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        valueLabel = new javax.swing.JLabel();
        value = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        nameLabel.setText(JndiRootNode.getLocalizedString("TXT_AttributeName"));
        nameLabel.setLabelFor(name);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 4, 4);
        add(nameLabel, gridBagConstraints);

        name.setColumns(16);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 4, 4, 8);
        add(name, gridBagConstraints);

        valueLabel.setText(JndiRootNode.getLocalizedString("TXT_AttributeValue"));
        valueLabel.setLabelFor(value);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 8, 4);
        add(valueLabel, gridBagConstraints);

        value.setColumns(16);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 8, 8);
        add(value, gridBagConstraints);

    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTextField value;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables

}