/*
 * The contents of this file are subject to the terms of the Common Development
 * and Distribution License (the License). You may not use this file except in
 * compliance with the License.
 *
 * You can obtain a copy of the License at http://www.netbeans.org/cddl.html
 * or http://www.netbeans.org/cddl.txt.
 *
 * When distributing Covered Code, include this CDDL Header Notice in each file
 * and include the License file at http://www.netbeans.org/cddl.txt.
 * If applicable, add the following below the CDDL Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * The Original Software is NetBeans. The Initial Developer of the Original
 * Software is Sun Microsystems, Inc. Portions Copyright 1997-2006 Sun
 * Microsystems, Inc. All Rights Reserved.
 */

package org.netbeans.modules.corba.wizard.panels;

import java.util.*;
import javax.swing.*;
import javax.swing.event.*;
import org.openide.*;
import org.openide.util.*;
import org.netbeans.modules.corba.wizard.CorbaWizardData;

/**
 *
 * @author  tzezula
 * @version
 */
public abstract class AbstractWizardPanel extends javax.swing.JPanel implements WizardDescriptor.Panel {

    private ArrayList list = new ArrayList();

    /** Creates new form AbstractWizardPanel */
    public AbstractWizardPanel() {
        initComponents ();
    }

    /** Get the current component
     *  @return the component
     */
    public java.awt.Component getComponent(){
        return this;
    }
  
    /** Return the Help Context for this panel
     */
    public HelpCtx getHelp () {
        return HelpCtx.DEFAULT_HELP;
    }
  
    public void fireChange (Object source) {
        ArrayList lst;
        synchronized (this){
            lst = (ArrayList) this.list.clone();
        }
        ChangeEvent event = new ChangeEvent(source);
        for (int i=0; i< lst.size(); i++){
            ChangeListener listener = (ChangeListener) lst.get(i);
            listener.stateChanged(event);
        }
    }
  
    public synchronized void addChangeListener (ChangeListener listener) {
        this.list.add(listener);
    }
  
    public synchronized void removeChangeListener (ChangeListener listener) {
        this.list.remove(listener);
    }
  
  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        setLayout(new java.awt.BorderLayout());
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
