/*
 *                 Sun Public License Notice
 * 
 * The contents of this file are subject to the Sun Public License
 * Version 1.0 (the "License"). You may not use this file except in
 * compliance with the License. A copy of the License is available at
 * http://www.sun.com/
 * 
 * The Original Code is NetBeans. The Initial Developer of the Original
 * Code is Sun Microsystems, Inc. Portions Copyright 1997-2001 Sun
 * Microsystems, Inc. All Rights Reserved.
 */

package org.netbeans.modules.corba.wizard.panels;

import org.netbeans.modules.corba.wizard.*;
/**
 *
 * @author  tzezula
 */
public class FilePanel extends AbstractWizardPanel implements javax.swing.event.DocumentListener {

    /** Creates new form FilePanel */
    public FilePanel() {
        initComponents();
        this.jTextField1.getDocument().addDocumentListener (this);
    }
    
    public void readCorbaSettings (CorbaWizardData data) {
        Object file = data.getBindingDetails();
        if (file != null && file instanceof java.io.File)
            this.jTextField1.setText (((java.io.File)file).getAbsolutePath());
    }
    
    public void storeCorbaSettings (CorbaWizardData data) {
        data.setBindingDetails ( new java.io.File (this.jTextField1.getText()));
    }

    public boolean isValid () {
    	return (this.jTextField1.getText() != null && this.jTextField1.getText().length() > 0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        setPreferredSize(new java.awt.Dimension(500, 340));
        
        name.setText(bundle.getString("TXT_BindingMethodDetails"));
        name.setFont(new java.awt.Font ("Dialog", 0, 18));
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridwidth = 0;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(8, 8, 4, 8);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints1.weightx = 1.0;
        add(name, gridBagConstraints1);
        
        
        jLabel2.setText(bundle.getString("TXT_IORFileName"));
        jLabel2.setLabelFor(name);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.insets = new java.awt.Insets(4, 8, 8, 4);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabel2, gridBagConstraints1);
        
        
        jTextField1.setToolTipText(bundle.getString("MSG_IORFileName"));
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(4, 4, 8, 4);
        gridBagConstraints1.weightx = 1.0;
        add(jTextField1, gridBagConstraints1);
        
        
        jButton1.setText(bundle.getString("TXT_Browse"));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browse(evt);
            }
        }
        );
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 2;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.insets = new java.awt.Insets(4, 4, 8, 8);
        add(jButton1, gridBagConstraints1);
        
        
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 2;
        gridBagConstraints1.gridwidth = 0;
        gridBagConstraints1.gridheight = 0;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.weightx = 1.0;
        gridBagConstraints1.weighty = 1.0;
        add(jPanel1, gridBagConstraints1);
        
    }//GEN-END:initComponents

    private void browse(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browse
        // Add your handling code here:
        javax.swing.JFileChooser fd = new javax.swing.JFileChooser();
        fd.setMultiSelectionEnabled(false);
        fd.setFileFilter ( new javax.swing.filechooser.FileFilter() {
            
            public boolean accept (java.io.File file) {
                if (file.isDirectory())
                    return true;
                else if (!file.exists()) 
                    return true;
                else if (file.getName().endsWith(".ior")) //NoI18N
                    return true;
                else
                    return false;
            }
            
            public String getDescription () {
                return org.openide.util.NbBundle.getBundle(FilePanel.class).getString("TXT_IORFileExt");
            }
        });
        if (fd.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            this.jTextField1.setText (fd.getSelectedFile().getAbsolutePath());
            this.fireChange (this);
        }
    }//GEN-LAST:event_browse

    public void changedUpdate(javax.swing.event.DocumentEvent event) {
        this.fireChange(this);
    }    

    public void removeUpdate(javax.swing.event.DocumentEvent event) {
        this.fireChange(this);
    }
    
    public void insertUpdate(javax.swing.event.DocumentEvent event) {
        this.fireChange(this);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel name;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private static final java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/netbeans/modules/corba/wizard/panels/Bundle");    

}
