/* DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
/*
/* Copyright 1997-2007 Sun Microsystems, Inc. All rights reserved.
/*
/* The contents of this file are subject to the terms of either the GNU
/* General Public License Version 2 only ("GPL") or the Common
/* Development and Distribution License("CDDL") (collectively, the
/* "License"). You may not use this file except in compliance with the
/* License. You can obtain a copy of the License at
/* http://www.netbeans.org/cddl-gplv2.html
/* or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
/* specific language governing permissions and limitations under the
/* License.  When distributing the software, include this License Header
/* Notice in each file and include the License file at
/* nbbuild/licenses/CDDL-GPL-2-CP.  Sun designates this
/* particular file as subject to the "Classpath" exception as provided
/* by Sun in the GPL Version 2 section of the License file that
/* accompanied this code. If applicable, add the following below the
/* License Header, with the fields enclosed by brackets [] replaced by
/* your own identifying information:
/* "Portions Copyrighted [year] [name of copyright owner]"
/*
/* Contributor(s): */
/*
 * CatHairLengthPanel.java
 *
 * Created on August 9, 2005, 10:58 PM */
package wizarddemo.panels;

import java.util.Map;
import javax.swing.JRadioButton;
import org.netbeans.spi.wizard.WizardController;

/**
 *
 * @author  Timothy Boudreau
 */
public class CatHairLengthPanel extends javax.swing.JPanel {
    public static final String KEY_HAIR = "hairLength";
    public static final String VALUE_SHORT = "shortHair";
    public static final String VALUE_LONG = "longHair";
    
    private final WizardController controller;
    private final Map wizardData;
    
    /** Creates new form CatHairLengthPanel */
    public CatHairLengthPanel(WizardController controller, Map wizardData) {
        initComponents();
        
        this.controller = controller;
        this.wizardData = wizardData;
        
        longHairButton.putClientProperty (KEY_HAIR, VALUE_LONG);
        shortHairButton.putClientProperty(KEY_HAIR, VALUE_SHORT);
        controller.setProblem ("No hair length selected");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        longHairButton = new javax.swing.JRadioButton();
        shortHairButton = new javax.swing.JRadioButton();

        setLayout(new java.awt.GridLayout(2, 1));

        setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 5, 1, 1)));
        buttonGroup1.add(longHairButton);
        longHairButton.setText("Long hair");
        longHairButton.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(0, 0, 0, 0)));
        longHairButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        longHairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairSelected(evt);
            }
        });

        add(longHairButton);

        buttonGroup1.add(shortHairButton);
        shortHairButton.setText("Short hair");
        shortHairButton.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(0, 0, 0, 0)));
        shortHairButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        shortHairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairSelected(evt);
            }
        });

        add(shortHairButton);

    }
    // </editor-fold>//GEN-END:initComponents

    private void hairSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairSelected
        
        Object val = ((JRadioButton ) evt.getSource()).getClientProperty(KEY_HAIR);
        wizardData.put (KEY_HAIR, val);
        controller.setProblem (null);
        
    }//GEN-LAST:event_hairSelected
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton longHairButton;
    private javax.swing.JRadioButton shortHairButton;
    // End of variables declaration//GEN-END:variables
    
}
