/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.netbeans.modules.wsdlextensions.ldap;

import java.awt.Frame;
import javax.swing.JPanel;
import org.netbeans.modules.wsdlextensions.ldap.utils.LdapConnection;
import org.openide.WizardDescriptor;

public final class LDAPServerBrowserVisualPanel2 extends JPanel {
    private LdapConnection conn = null;
    /** Creates new form LDAPServerBrowserVisualPanel2 */
    public LDAPServerBrowserVisualPanel2() {
        initComponents();
        conn = new LdapConnection();
    }

    @Override
    public String getName() {
        return "LDAP Server Setting";
    }
    
    public void store(WizardDescriptor wd){
        conn.setUrl(jTextFieldLDAPServerURL.getText());
        conn.setDn(jTextFieldRootDN.getText());
        wd.putProperty("LDAP_CONNECTION", conn);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLDAPServerURL = new javax.swing.JLabel();
        jLabelRootDN = new javax.swing.JLabel();
        jTextFieldLDAPServerURL = new javax.swing.JTextField();
        jTextFieldRootDN = new javax.swing.JTextField();
        jButtonAdvanced = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(jLabelLDAPServerURL, "LDAP Server URL");

        org.openide.awt.Mnemonics.setLocalizedText(jLabelRootDN, "Root DN");

        org.openide.awt.Mnemonics.setLocalizedText(jButtonAdvanced, "Advanced");
        jButtonAdvanced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdvancedActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(52, 52, 52)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jButtonAdvanced)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabelRootDN)
                            .add(jLabelLDAPServerURL))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jTextFieldRootDN)
                            .add(jTextFieldLDAPServerURL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 169, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(27, 27, 27)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelLDAPServerURL)
                    .add(jTextFieldLDAPServerURL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelRootDN)
                    .add(jTextFieldRootDN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonAdvanced)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdvancedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdvancedActionPerformed
        // TODO add your handling code here:
        AdvancedLoginDialog dlg = new AdvancedLoginDialog(new Frame(), true, conn);
        dlg.setVisible(true);
    }//GEN-LAST:event_jButtonAdvancedActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdvanced;
    private javax.swing.JLabel jLabelLDAPServerURL;
    private javax.swing.JLabel jLabelRootDN;
    private javax.swing.JTextField jTextFieldLDAPServerURL;
    private javax.swing.JTextField jTextFieldRootDN;
    // End of variables declaration//GEN-END:variables
}

