/*
 * The contents of this file are subject to the terms of the Common Development
 * and Distribution License (the License). You may not use this file except in
 * compliance with the License.
 *
 * You can obtain a copy of the License at http://www.netbeans.org/cddl.html
 * or http://www.netbeans.org/cddl.txt.
 *
 * When distributing Covered Code, include this CDDL Header Notice in each file
 * and include the License file at http://www.netbeans.org/cddl.txt.
 * If applicable, add the following below the CDDL Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * The Original Software is NetBeans. The Initial Developer of the Original
 * Software is Sun Microsystems, Inc. Portions Copyright 1997-2006 Sun
 * Microsystems, Inc. All Rights Reserved.
 */
/*
 * SaveAsUI.java
 *
 * Created on August 5, 2007, 5:22 PM
 */

package org.netbeans.modules.perspective.ui;

import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.netbeans.modules.perspective.utils.PerspectiveManagerImpl;
import org.netbeans.modules.perspective.persistence.PerspectivePreferences;
import org.netbeans.modules.perspective.utils.CurrentPerspectiveReader;
import org.netbeans.modules.perspective.views.Perspective;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.NbBundle;
import org.openide.windows.WindowManager;

/**
 *
 * @author  Anurdha
 */
public class SaveAsUI extends javax.swing.JDialog {

    private static final long serialVersionUID = 1l;
    private DefaultListModel defaultListModel = new DefaultListModel();
    private static String Here = NbBundle.getMessage(SaveAsUI.class,"HERE");
    private Perspective selected;

    /** Creates new form SaveAsUI */
    private SaveAsUI() {
        super(WindowManager.getDefault().getMainWindow(), true);
        initComponents();
        modeList.setModel(defaultListModel);
        modeList.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {

                Perspective perspective = (Perspective) modeList.getSelectedValue();
                if (perspective != null) {
                    txtName.setText(perspective.getAlias());
                    selected = perspective;

                    before.setSelected(perspective.isBeforeSeparator());
                    after.setSelected(perspective.isAfterSeparator());
                    loadcmbPerspectives();
                    cmbPosition.setSelectedIndex(perspective.getIndex());
                } else {
                    selected = null;
                    loadcmbPerspectives();
                }
                
                validateName();
            }
        });
        loadcmbPerspectives();
        loadPerspectives();
        validateName();
    }

    private void clear() {
        before.setSelected(false);
        after.setSelected(false);
    }

    private void loadPerspectives() {
        defaultListModel.clear();
        List<Perspective> perspectives = PerspectiveManagerImpl.getInstance().getPerspectives();
        for (Perspective perspective : perspectives) {
            defaultListModel.addElement(perspective);
        }
    }

    private void loadcmbPerspectives() {
        List<Perspective> perspectives = PerspectiveManagerImpl.getInstance().getPerspectives();
        cmbPosition.removeAllItems();
        if (perspectives.size() == 0) {
            cmbPosition.addItem(Here);
            return;
        }
        String prev = "";
        for (Perspective perspective : perspectives) {
            if (perspective.equals(selected)) {
                continue;
            }
            if (prev.isEmpty()) {
                cmbPosition.addItem(Here + " - " + perspective.getAlias());
            } else {
                cmbPosition.addItem(prev + Here + " - " + perspective.getAlias());
            }
            prev = perspective.getAlias() + " - ";
        }
        cmbPosition.addItem(prev + Here);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        modeList = new javax.swing.JList();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        cmbPosition = new javax.swing.JComboBox();
        after = new javax.swing.JCheckBox();
        before = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(SaveAsUI.class, "SaveAsUI.title")); // NOI18N
        setResizable(false);

        btnCancel.setAction(new CancelAction());
        btnCancel.setText(org.openide.util.NbBundle.getMessage(SaveAsUI.class, "SaveAsUI.btnCancel.text")); // NOI18N

        btnOK.setAction(new SaveAs());
        btnOK.setText(org.openide.util.NbBundle.getMessage(SaveAsUI.class, "SaveAsUI.btnOK.text")); // NOI18N

        modeList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(modeList);

        lblName.setText(NbBundle.getMessage(SaveAsUI.class,"Name")); // NOI18N

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        lblDescription.setText(NbBundle.getMessage(SaveAsUI.class,"Saveas_Header")); // NOI18N

        lblPosition.setText(NbBundle.getMessage(SaveAsUI.class,"SaveAsUI.lblPosition.text")); // NOI18N

        after.setText(org.openide.util.NbBundle.getMessage(SaveAsUI.class, "SaveAsUI.after.text")); // NOI18N
        after.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        after.setMargin(new java.awt.Insets(0, 0, 0, 0));

        before.setText(org.openide.util.NbBundle.getMessage(SaveAsUI.class, "SaveAsUI.before.text")); // NOI18N
        before.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        before.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel1.setText(org.openide.util.NbBundle.getMessage(SaveAsUI.class, "SaveAsUI.jLabel1.text")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(btnOK)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnCancel))
                    .add(lblDescription)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblPosition, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(lblName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(before)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(after))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, txtName)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, cmbPosition, 0, 239, Short.MAX_VALUE)))))
                    .add(jLabel1))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {btnCancel, btnOK}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(lblDescription)
                .add(8, 8, 8)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblName)
                    .add(txtName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblPosition)
                    .add(cmbPosition, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(before)
                    .add(after))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 163, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnCancel)
                    .add(btnOK))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        validateName();
        validateExist();
    }//GEN-LAST:event_txtNameKeyReleased

    public static void createSaveAsUI() {
        SaveAsUI saveAsUI = new SaveAsUI();
        saveAsUI.pack();
        saveAsUI.setLocationRelativeTo(null);
        saveAsUI.setVisible(true);
    }

    private class CancelAction extends AbstractAction {

        private static final long serialVersionUID = 1l;
        Perspective mode;

        public CancelAction() {
            putValue(NAME, NbBundle.getMessage(SaveAsUI.class,"Cancel"));
        }

        public void actionPerformed(ActionEvent e) {
            dispose();
        }
    }

    private void validateName() {
        if (txtName.getText().isEmpty()) {
            btnOK.setEnabled(false);
        } else {
            btnOK.setEnabled(true);
        }
    }

    private void validateExist() {
        String id = txtName.getText();
        Perspective perspective = PerspectiveManagerImpl.getInstance().findPerspectiveByAlias(id);
        if (perspective != null) {
            modeList.setSelectedValue(perspective, true);
        } else {
            modeList.clearSelection();
            clear();
        }
    }

    private void saveAsMutilMode() {
        Perspective perspective = (Perspective) modeList.getSelectedValue();
        if (perspective != null) {
            NotifyDescriptor d = new NotifyDescriptor.Confirmation("'"+perspective.getAlias()+ java.util.ResourceBundle.getBundle("org/netbeans/modules/perspective/ui/Bundle").getString("OverWrite_Massage"), java.util.ResourceBundle.getBundle("org/netbeans/modules/perspective/ui/Bundle").getString("Overwrite_MultiMode_View"),
                    NotifyDescriptor.YES_NO_OPTION);
            if (DialogDisplayer.getDefault().notify(d) != NotifyDescriptor.YES_OPTION) {
                return;
            }
            PerspectiveManagerImpl.getInstance().deregisterPerspective(perspective);
            perspective.clear();
        }else{
         
         perspective = new Perspective(PerspectivePreferences.getInstance().getCustomPerspectiveName(),
                 txtName.getText().trim());
         Perspective selectedPerspective=PerspectiveManagerImpl.getInstance().getSelected();
         perspective.setImagePath(selectedPerspective.getImagePath());
        }
        

        new CurrentPerspectiveReader(perspective);
        perspective.setBeforeSeparator(before.isSelected());
        perspective.setAfterSeparator(after.isSelected());
        PerspectiveManagerImpl.getInstance().registerPerspective(cmbPosition.getSelectedIndex(), perspective);
        PerspectiveManagerImpl.getInstance().setSelected(perspective);
        ToolbarStyleSwitchUI.getInstance().loadQuickPerspectives();
        dispose();
    }

    private class SaveAs extends AbstractAction {

        private static final long serialVersionUID = 1l;
        Perspective mode;

        public SaveAs() {
            putValue(NAME, NbBundle.getMessage(SaveAsUI.class,"OK"));
        }

        public void actionPerformed(ActionEvent e) {
            saveAsMutilMode();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox after;
    private javax.swing.JCheckBox before;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox cmbPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JList modeList;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
