/*
 *                 Sun Public License Notice
 *
 * The contents of this file are subject to the Sun Public License
 * Version 1.0 (the "License"). You may not use this file except in
 * compliance with the License. A copy of the License is available at
 * http://www.sun.com/
 *
 * The Original Code is NetBeans. The Initial Developer of the Original
 * Code is Sun Microsystems, Inc. Portions Copyright 1997-2002 Sun
 * Microsystems, Inc. All Rights Reserved.
 */

package org.netbeans.modules.assistant.parsing;

import org.xml.sax.*;

/*
 * File:           DefaultAssistantHandler.java
 * Date:           October 22, 2002  5:15 PM
 *
 * @author  Richard Gregor
 * @version generated by NetBeans XML module
 */
public class DefaultAssistantHandler implements AssistantHandler {
    
    public static final boolean DEBUG = false;
    
    public void handle_item(final java.lang.String data, final AttributeList meta) throws SAXException {
        if (DEBUG) System.err.println("handle_item: " + data);
    }
    
    public void start_section(final AttributeList meta) throws SAXException {
        if (DEBUG) System.err.println("start_section: " + meta);
    }
    
    public void end_section() throws SAXException {
        if (DEBUG) System.err.println("end_section()");
    }
    
    public void start_assistant(final AttributeList meta) throws SAXException {
        if (DEBUG) System.err.println("start_assistant: " + meta);
    }
    
    public void end_assistant() throws SAXException {
        if (DEBUG) System.err.println("end_assistant()");
    }
    
    public void handle_name(final java.lang.String data, final AttributeList meta) throws SAXException {
        if (DEBUG) System.err.println("handle_name: " + data);
    }
    
    public void start_id(final AttributeList meta) throws SAXException {
        if (DEBUG) System.err.println("start_id: " + meta);
    }
    
    public void end_id() throws SAXException {
        if (DEBUG) System.err.println("end_id()");
    }
    
}

