/*
 *                 Sun Public License Notice
 * 
 * The contents of this file are subject to the Sun Public License
 * Version 1.0 (the "License"). You may not use this file except in
 * compliance with the License. A copy of the License is available at
 * http://www.sun.com/
 * 
 * The Original Code is NetBeans. The Initial Developer of the Original
 * Code is Sun Microsystems, Inc. Portions Copyright 1997-2001 Sun
 * Microsystems, Inc. All Rights Reserved.
 */

package org.netbeans.modules.corba.wizard.nodes.gui;

import org.netbeans.modules.corba.wizard.nodes.utils.IdlUtilities;
/**
 *
 * @author  tzezula
 */
public class ForwardDclPanel extends ExPanel implements javax.swing.event.DocumentListener, java.awt.event.ActionListener {

    javax.swing.ButtonGroup group = new javax.swing.ButtonGroup();
    
    /** Creates new form FrowardDclPanel */
    public ForwardDclPanel() {
        initComponents();
        postInitComponents();
    }
    
    
    private void postInitComponents () {
        this.group.add (this.intf);
        this.group.add (this.vt);
        this.intf.setSelected (true);
        this.jTextField1.getDocument().addDocumentListener (this);
        this.intf.addActionListener(this);
        this.vt.addActionListener (this);
        this.jLabel1.setDisplayedMnemonic (this.bundle.getString("TXT_ModuleName_MNE").charAt(0));
        this.vt.setMnemonic (this.bundle.getString("TXT_ValueType_MNE").charAt(0));
        this.intf.setMnemonic (this.bundle.getString("TXT_Interface_MNE").charAt(0));
    }
    
    
    public String getName () {
        return this.jTextField1.getText().trim();
    }
    
    public void setName (String name) {
        this.jTextField1.setText (name);
    }
    
    public boolean isInterface () {
        return this.intf.isSelected();
    }
    
    public boolean isValuetype () {
        return this.vt.isSelected();
    }
    
    public void setInterface (boolean value) {
        if (value)
            this.intf.setSelected (true);
        else
            this.vt.setSelected (true);
    }
    
    public void setValuetype (boolean value) {
        if (value)
            this.vt.setSelected (true);
        else
            this.intf.setSelected (true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        intf = new javax.swing.JRadioButton();
        vt = new javax.swing.JRadioButton();

        setLayout(new java.awt.GridBagLayout());

        setPreferredSize(new java.awt.Dimension(250, 100));
        jLabel1.setText(bundle.getString("TXT_ModuleName"));
        jLabel1.setLabelFor(jTextField1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 4, 4);
        add(jLabel1, gridBagConstraints);

        jTextField1.setToolTipText(bundle.getString("TIP_FwdName"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 4, 4, 8);
        add(jTextField1, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        intf.setToolTipText(bundle.getString("TIP_InterfaceFwd"));
        intf.setText(bundle.getString("TXT_Interface"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
        jPanel1.add(intf, gridBagConstraints);

        vt.setToolTipText(bundle.getString("TIP_FwdValue"));
        vt.setText(bundle.getString("TXT_ValueType"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        jPanel1.add(vt, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 8, 8);
        add(jPanel1, gridBagConstraints);

    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton vt;
    private javax.swing.JRadioButton intf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private static final java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/netbeans/modules/corba/wizard/nodes/gui/Bundle");    

    private void checkState () {
        if (IdlUtilities.isValidIDLIdentifier(this.jTextField1.getText()))
            this.enableOk();
        else
            this.disableOk();
    }
    
    public void changedUpdate(javax.swing.event.DocumentEvent p1) {
        checkState();
    }
    
    public void removeUpdate(javax.swing.event.DocumentEvent p1) {
        checkState();
    }
    
    public void insertUpdate(javax.swing.event.DocumentEvent p1) {
        checkState();
    }
    
    public void actionPerformed (java.awt.event.ActionEvent event) {
        checkState();
    }
    
}
